### ISSUE TITLE
Help is needed - telegram.error.NetworkError

### ISSUE THREAD

**Issue by MBudkin** [n3d1117/chatgpt-telegram-bot#105]
No matter what I do, no matter how hard I try, this error appears. The Internet, of course, is available.

```
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed
```

**Comment by h3lp1ngh4nd** [comment]
Do you have the PROXY option enabled in .env? Comment it out in see if that changes anything.

**Comment by MBudkin** [comment]
> Duplicate of #81 and #97. Just delete everything you don't need from the `.env` file, especially the line with `PROXY` :)
> Do you have the PROXY option enabled in .env? Comment it out in see if that changes anything.

I spent 2 hours to solve this problem - but without success!
Removed everything superfluous - and everything worked, thanks!
I'm only new to GitHub and didn't pay attention to closed issues (bugs).
Thank you and good luck!
