### ISSUE TITLE
 An error has occurred  Unknown encoding gpt-3.5-turbo

### ISSUE THREAD

**Issue by TheTeggiy** [n3d1117/chatgpt-telegram-bot#109]
![image](https://user-images.githubusercontent.com/52865944/227597383-29839ea5-128c-45b5-a958-c181347e5907.png)

When I change the ChatGPT version at GPT-3.5 (instead of GPT-3.5-Turbo) I get the "Unknown Encoding GPT-3.5-Turbo" error

![image](https://user-images.githubusercontent.com/52865944/227598152-78bd9136-bdee-4c7c-b4f3-acde512c07fe.png)

**Comment by AlexHTW** [comment]
Hi @TheTeggiy, there is no openai model called "gpt-3.5".
The only 3.5 chat models available are gpt-3.5-turbo and gpt-3.5-0301, see [here](https://platform.openai.com/docs/models/gpt-3-5).
