### ISSUE TITLE
Help... how to fix this?

### ISSUE THREAD

**Issue by xBabylonia** [n3d1117/chatgpt-telegram-bot#11]
![image](https://user-images.githubusercontent.com/116042240/206393296-5b029cc4-f44b-4f4b-87e0-1588b77927c4.png)

**Comment by n3d1117** [comment]
Hi @xBabylonia, make sure you're using Python 3.10+ and have installed the dependencies correctly. 
`python-telegram-bot` must be exactly version `20.0a6`

**Comment by n3d1117** [comment]
Closing for now, feel free to reopen if issue persists
