### ISSUE TITLE
VOICE_REPLY_WITH_TRANSCRIPT_ONLY issue

### ISSUE THREAD

**Issue by lacer2k** [n3d1117/chatgpt-telegram-bot#114]
hi, i'm using docker, if in the .env file i set VOICE_REPLY_WITH_TRANSCRIPT_ONLY="false" i have this message: "Failed to transcribe text: 'async_generator' object has no attribute 'choices'" in the chat and these in the docker log:

chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2023-03-26 13:07:31,372 - root - ERROR - 'async_generator' object has no attribute 'choices'
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Traceback (most recent call last):
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 259, in transcribe
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     response, total_tokens = await self.openai.get_chat_response(chat_id=chat_id, query=transcript)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 55, in get_chat_response
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     if len(response.choices) > 1 and self.config['n_choices'] > 1:
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | AttributeError: 'async_generator' object has no attribute 'choices'

if i set VOICE_REPLY_WITH_TRANSCRIPT_ONLY="true" i have the right transcription, but no reply from chatgpt.

thanks for support.
best.
lacer2k

**Comment by n3d1117** [comment]
Oof, nice catch @lacer2k! Should be fixed now, can you do a `git pull` and try again?

**Comment by lacer2k** [comment]
sure trying now ;)

**Comment by lacer2k** [comment]
now in chat says "Failed to download audio file: [Errno 2] No such file or directory: 'AgADQA4AAnuXAAFR'. Make sure the file is not too large. (max 20MB)"

and in log "chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2023-03-26 13:43:51,713 - root - INFO - Resetting the conversation for user @lacer2k...
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2023-03-26 13:43:55,289 - root - ERROR - [Errno 2] No such file or directory: 'AgADQA4AAnuXAAFR'
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Traceback (most recent call last):
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 196, in transcribe
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/telegram/_files/file.py", line 215, in download_to_drive
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     filename.write_bytes(buf)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/pathlib.py", line 1275, in write_bytes
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     with self.open(mode='wb') as f:
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/pathlib.py", line 1252, in open
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return io.open(self, mode, buffering, encoding, errors, newline,
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/pathlib.py", line 1120, in _opener
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     return self._accessor.open(self, flags, mode)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | FileNotFoundError: [Errno 2] No such file or directory: 'AgADQA4AAnuXAAFR'"

**Comment by n3d1117** [comment]
weird, does it happen all the time? can you try with a different audio?

**Comment by lacer2k** [comment]
i have VOICE_REPLY_WITH_TRANSCRIPT_ONLY="false" now transcription works, but system give me no reply

Attaching to chatgpt-telegram-bot-chatgpt-telegram-bot-1
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2023-03-26 14:03:09,822 - telegram.ext._application - INFO - Application started
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2023-03-26 14:03:18,850 - root - INFO - User @lacer2k requested their usage statistics
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2023-03-26 14:03:36,173 - root - INFO - New transcribe request received from user @lacer2k
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 2023-03-26 14:03:38,022 - openai - INFO - message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=1387 request_id=2e37b23d29b5dd273a27c20582aeabef response_code=200

**Comment by lacer2k** [comment]
i rebooted the server and now works perfectly!
