### ISSUE TITLE
[Suggest] add bing chat feature

### ISSUE THREAD

**Issue by Am1nCmd** [n3d1117/chatgpt-telegram-bot#115]
I have searching for a repository, seems there a lot of using bing chat that already using GPT-4 and connect to internet using the cookies https://github.com/acheong08/EdgeGPT 

I think it would be usefull

**Comment by n3d1117** [comment]
Hi @Am1nCmd, I think it's a bit out of scope for this project and I'd rather work with official APIs only. Closing this for now

**Comment by Geczy** [comment]
+1 also requesting this
