### ISSUE TITLE
returns an error related to ffmpeg

### ISSUE THREAD

**Issue by Allfrey** [n3d1117/chatgpt-telegram-bot#118]
chatgpt-telegram-bot\venv\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

**Comment by n3d1117** [comment]
Hi @Allfrey, as stated in the README you might need ffmpeg for audio transcriptions to work correctly.
Check out the pydub documentation on this: https://github.com/jiaaro/pydub#getting-ffmpeg-set-up

**Comment by Allfrey** [comment]
I'm a zero programmer and I don't understand anything. What I need to do to make audio transcription work.
