### ISSUE TITLE
Help! ERROR

### ISSUE THREAD

**Issue by stewiemax21** [n3d1117/chatgpt-telegram-bot#120]
![Снимок](https://user-images.githubusercontent.com/129033052/227850586-0098bea7-5a6e-4908-b9d1-1b32b93329ad.JPG)
in the file .env all tokens are entered
# Your OpenAI API key
OPENAI_API_KEY = "my key"

# Your Telegram bot token obtained using @BotFather
TELEGRAM_BOT_TOKEN = "my key"

# Telegram user ID of admins, or - to assign no admin.
ADMIN_USER_IDS = "348763539"

# Comma separated list of telegram user IDs, or * to allow all.
ALLOWED_TELEGRAM_USER_IDS = "*"

2023-03-27 12:32:06,331 - root - ERROR - The following environment values are missing in your .env: TELEGRAM_BOT_TOKEN, OPENAI_API_KEY  in the file .env all tokens are entered

**Comment by n3d1117** [comment]
Hey there @stewiemax21, can you double check that your env file is named exactly `.env` and is located in the `chatgpt-telegram-bot-main` folder?

**Comment by ARST1771** [comment]
Solved! An error is occured with .env file type. You should open "view" and show file type then delete `.example` and bot'll start working

**Comment by MrPipp** [comment]
I also encountered an error.
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/37713623/4eab39fa-63a9-4383-aefc-267e52c5b646)
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/37713623/616f28df-ab28-44ee-94a5-5fc6219364fc)
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/37713623/eeb68eec-86ed-41f1-9753-723da672dec8)
What could be the reason?

**Comment by n3d1117** [comment]
@MrPipp make sure your python version is >= 3.9
