### ISSUE TITLE
GPT-4 not working

### ISSUE THREAD

**Issue by NostromoUS** [n3d1117/chatgpt-telegram-bot#125]
Hi all,

I just got access to GPT-4 API and it looks like it's not working? I changed OPENAI_MODEL to "gpt-4" and the bot states it's gpt3.5-turbo when asked. I also tried changing in the main.py which is what this variable is doing anyway. gpt-4-32k states an error communicating with openAI.

Any ideas? Even though I got the e-mail saying I now have access, I also tried issuing a new API key, same results.

**Comment by n3d1117** [comment]
Hi @NostromoUS, since you changed OPENAI_MODEL to "gpt-4" and didn't get any errors, you're probably already using gpt-4, otherwise you'd receive an error (i.e. I don't have gpt-4 access and it says "The model gpt-4 doesn't exist").

I wouldn't give much thought to the bot saying it's gpt3.5. Could you try asking for a task only gpt-4 could solve, like a complex mathematical problem?

Not sure what's going on with `gpt-4-32k` giving communication errors though. Will keep this issue open in case someone else with gpt-4 access wants to help.

**Comment by BjornB2** [comment]
My gpt-4 didn't work either this morning. Probably just a problem with the API at their side. Now it works again.

**Comment by NostromoUS** [comment]
> Hi @NostromoUS, since you changed OPENAI_MODEL to "gpt-4" and didn't get any errors, you're probably already using gpt-4, otherwise you'd receive an error (i.e. I don't have gpt-4 access and it says "The model gpt-4 doesn't exist").
> 
> I wouldn't give much thought to the bot saying it's gpt3.5. Could you try asking for a task only gpt-4 could solve, like a complex mathematical problem?
> 
> Not sure what's going on with `gpt-4-32k` giving communication errors though. Will keep this issue open in case someone else with gpt-4 access wants to help.

Gotcha. Yeah, gpt-4 isn't giving any errors and it's working, so I'm guessing it's got to be using it.

If I may, instead of opening another issue, may I ask a quick question regarding MAX_TOKENS? As I'm using gpt-4 now I should be able to change this value to 8,192 if I so wish correct?

**Comment by n3d1117** [comment]
> may I ask a quick question regarding MAX_TOKENS? As I'm using gpt-4 now I should be able to change this value to 8,192 if I so wish correct?

Correct. Keep in mind that (afaik) if you set [max_tokens](https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens) to the highest value possible (8,192) it might not be able to keep some buffer for subsequent responses. For gpt-4 i'd set it somewhere around 5000 at max, unless you need super long answers

**Comment by rakshitharao16** [comment]
my gpt repharse not working in telegram what i have to do for this
