### ISSUE TITLE
Allow to disable image generation and transcription in the config

### ISSUE THREAD

**Issue by PeterDaveHello** [n3d1117/chatgpt-telegram-bot#129]
That's something that can help control the budget 🤩

**Comment by n3d1117** [comment]
Hi @PeterDaveHello, you mean disable those features altogether for everyone?

**Comment by PeterDaveHello** [comment]
> Hi @PeterDaveHello, you mean disable those features altogether for everyone?

yes, as the owner of the bot, has the ability to disable the feature will be great, thanks!

**Comment by n3d1117** [comment]
Hi @PeterDaveHello, just published the [`allow-disable-transcription-and-image-generation`](https://github.com/n3d1117/chatgpt-telegram-bot/tree/feature/allow-disable-transcription-and-image-generation) branch which allows disabling image generation and transcriptions in .env:

```
ENABLE_TRANSCRIPTION="false"
ENABLE_IMAGE_GENERATION="false"
```

Both are true by default. Let me know what you think!

**Comment by PeterDaveHello** [comment]
@n3d1117 awesome 👍
