### ISSUE TITLE
Support to allow admin and user by username, not just ID

### ISSUE THREAD

**Issue by PeterDaveHello** [n3d1117/chatgpt-telegram-bot#130]
It's easier to retrieve and maintain username in the list, ID is not 😅

**Comment by n3d1117** [comment]
I might be wrong (maybe @AlexHTW can help me here), but if we use usernames then we have no way of checking if a user is a member of a group (this logic used to calculate budget in group chats)

**Comment by AlexHTW** [comment]
Hey @PeterDaveHello,
I understand your issue with the IDs, however I think it it is not safe to usernames as identifiers. For one, a user can use legacy user names without the "@" which can be anything and not unique. Secondly, usernames can be changed, your user would lose access.
I think your issues can be helped by adding the user ID to the log outputs. That way you would always be aware about the ID connected to a username.
To add a new user they could send a message to the bot and you would see their ID in the log and can copy paste it. I made a PR #134, adding the username to every log output (@n3d1117 we can also limit it to only some of them, but I don't think it hurts everywhere).

Additionally, I recommend you add a comment line in your .env above/below the ALLOWED_TELEGRAM_USER_IDS with a list of the according username. For example:
```
# usernames: peter, jack, mary, chris
ALLOWED_TELEGRAM_USER_IDS="12334,345353,2342123,234234"
```

**Comment by n3d1117** [comment]
Closing this as using usernames doesn't seem feasible. For further improvements see #108
