### ISSUE TITLE
/setinline 

### ISSUE THREAD

**Issue by Newfpv** [n3d1117/chatgpt-telegram-bot#133]
I still don't understand how it works. configured in bot father, trying to run via @username_bot and it doesn't load anything. Even with a request

**Comment by Geczy** [comment]
set the bot to admin in the group. will work after

**Comment by n3d1117** [comment]
Hi @Newfpv, are you using the bot in a private chat? or in a group?

**Comment by Geczy** [comment]
write your question here

**Comment by JohanChungus** [comment]
I use Inlinemode on private chat but nothing happend

**Comment by n3d1117** [comment]
@JohanChungus inline mode in private chats will be available when #101 is merged

**Comment by JohanChungus** [comment]
> @JohanChungus inline mode in private chats will be available when #101 is merged

So I Need Waiting?

**Comment by n3d1117** [comment]
Yes!

**Comment by JohanChungus** [comment]
Hmm I need waiting 😐

**Comment by JohanChungus** [comment]
What About now is working?
