### ISSUE TITLE
Moving to GPT-4

### ISSUE THREAD

**Issue by otakukz17** [n3d1117/chatgpt-telegram-bot#136]
Hi
I got access to the api gpt-4 today and wanted to try to use it in the telegram bot.
How do I do it?
I tried in main.py to change the model from gpt-3.5-turbo to gpt-4, but when I try to write to the bot it gives an error 
"Failed to get response: ⚠️ _OpenAI Invalid request_ ⚠️
This model's maximum context length is 8192 tokens. However, you requested 8268 tokens (76 in the messages, 8192 in the completion). Please reduce the length of the messages or completion."
The /reset command doesn't seem to work, even though it says "Done!"
I'll be glad for any help

**Comment by h3lp1ngh4nd** [comment]
Use a MAX_TOKENS setting in the .env of like 7800-8000, this should do the trick for now.

**Comment by otakukz17** [comment]
@h3lp1ngh4nd Thank you! It's working. I just changed the model and Max_tokens again and restarted the bot and now there is no error and in the personal cabinet OpenAI fixes that I now use GPT-4
