### ISSUE TITLE
The bot forget its role

### ISSUE THREAD

**Issue by misterkisus** [n3d1117/chatgpt-telegram-bot#144]
the bot forgets its role every time it wipes its memory after a token overflow

**Comment by n3d1117** [comment]
Hi @misterkisus what's a token overflow? Do you mean it loses track of the conversation when bot is stopped?

**Comment by n3d1117** [comment]
@misterkisus You can either:
- disable privacy mode, so that the bot reads every message in the group
- use `GROUP_TRIGGER_KEYWORD` and make the other bot prefix message with the trigger keyword

**Comment by misterkisus** [comment]
I did as you wrote, but it still only responds when you forward its messages, or use the inline function
