### ISSUE TITLE
Monthly budget issue

### ISSUE THREAD

**Issue by muhammed540** [n3d1117/chatgpt-telegram-bot#150]
While all users are allowed, I cannot set a monthly budget limit. A warning appears that you have reached the monthly limit and the budget is 0 dollars.

.env:

```
# Your OpenAI API key
OPENAI_API_KEY="---"

# Your Telegram bot token obtained using @BotFather
TELEGRAM_BOT_TOKEN="---"

# Telegram user ID of admins, or - to assign no admin.
ADMIN_USER_IDS="1968082698"

# Comma separated list of telegram user IDs, or * to allow all.
ALLOWED_TELEGRAM_USER_IDS="*"

MONTHLY_USER_BUDGETS="3.0"
GROUP_TRIGGER_KEYWORD="gpt"
```

**Comment by AlexHTW** [comment]
Hey @muhammed540 , you are right. 
There is currently no real implemention of budgets for a "*" - user list. Budgets are just ignored if everybody is allowed. The warning and /stats output is of course not great.
I am working on an improvement. 
I was thinking that for a * user list every user would get the budget in the first position of the budget list. Example:
```
ALLOWED_TELEGRAM_USER_IDS="*"
MONTHLY_USER_BUDGETS="10.0"
```
The bot would give every user their own $10 budget.
What would be your desired behavior?
Looking forward to your input

**Comment by muhammed540** [comment]
> Hey @muhammed540 , you are right. There is currently no real implemention of budgets for a "*" - user list. Budgets are just ignored if everybody is allowed. The warning and /stats output is of course not great. I am working on an improvement. I was thinking that for a * user list every user would get the budget in the first position of the budget list. Example:
> 
> ```
> ALLOWED_TELEGRAM_USER_IDS="*"
> MONTHLY_USER_BUDGETS="10.0"
> ```
> 
> The bot would give every user their own $10 budget. What would be your desired behavior? Looking forward to your input

this is exactly the feature I wanted. thanks

**Comment by muhammed540** [comment]
@AlexHTW Access to the balance using the API is now restricted. Will this affect the development of this feature? #163

**Comment by AlexHTW** [comment]
Hey @muhammed540, the API part that was removed was only used for the /stats command of admins, giving OpenAI account information - `grant` (now removed) and `billed this month` (still working, I suspect not for long).
For budgets we are tracking the daily usage of each user in the `/usage_logs`-files and calculating the spending with customizable (in the .env file) prices for each activity. The addition of this feature will also only use this.

One question about the feature - are you only interested in separate $10 budgets for every user or do you also think an option for shared budgets, so that $10 would be split between all users would be useful?
(Your last question somehow led me to believe you were actually thinking about the second option).
Another user [already requested](https://github.com/n3d1117/chatgpt-telegram-bot/issues/106#issuecomment-1489014011) shared budgets. So, if you also see value in that, I will try to include it in the budget update.

**Comment by muhammed540** [comment]
@AlexHTW  The reason I want this feature is that some users use the bot much more than others. I want to prevent this inequality by setting a limit for each user. I will charge according to the usage of the bot

**Comment by wearetyomsmnv** [comment]
@AlexHTW Is it possible to add an automatic change of api key - if it is all used.

**Comment by AlexHTW** [comment]
Hey @wearetyomsmnv. The same suggestion was made in #132.
Personally, I am not in favor of adding this features as it violates the Terms of use ([see 4.e](https://openai.com/policies/terms-of-use)).

**Comment by Newfpv** [comment]
> Hey @muhammed540 , you are right. There is currently no real implemention of budgets for a "*" - user list. Budgets are just ignored if everybody is allowed. The warning and /stats output is of course not great. I am working on an improvement. I was thinking that for a * user list every user would get the budget in the first position of the budget list. Example:
> 
> ```
> ALLOWED_TELEGRAM_USER_IDS="*"
> MONTHLY_USER_BUDGETS="10.0"
> ```
> 
> The bot would give every user their own $10 budget. What would be your desired behavior? Looking forward to your input

How is improvement progressing?

**Comment by AlexHTW** [comment]
Hey @Newfpv , I implemented it in PR #137. It's waiting for review and merge. 
Feel free to check it out and test it 🙂

**Comment by khanfar** [comment]
GROUP_TRIGGER_KEYWORD="gpt"    whats this ? and whats for ?

**Comment by n3d1117** [comment]
> GROUP_TRIGGER_KEYWORD="gpt" whats this ? and whats for ?

Please see the README for documentation

> If set, the bot in group chats will only respond to messages that start with this keyword

**Comment by AlexHTW** [comment]
@n3d1117 the original issue of this thread was added with the budget periods update, so I'd say it can be closed ✌️
