### ISSUE TITLE
Reply with /bot command

### ISSUE THREAD

**Issue by igorpanin** [n3d1117/chatgpt-telegram-bot#156]
Add the ability to reply to messages using the /bot command, providing instructions to the assistant on what to do and how to reply

If possible to do in private chats — would be great as well

Something like this (group chats):

![b7d5747d20fae9a965fd44161a916c41](https://user-images.githubusercontent.com/125222668/229278034-6c22afa2-0187-4591-8fe3-39899980e7ae.jpeg)

**Comment by n3d1117** [comment]
@igorpanin this is now possible thanks to @stanislavlysenko0912 in #298!
