### ISSUE TITLE
quota issues

### ISSUE THREAD

**Issue by lacer2k** [n3d1117/chatgpt-telegram-bot#158]
hi everyone,
telegram reply to my messages:

Failed to get response: ⚠️ OpenAI Rate Limit exceeded ⚠️
You exceeded your current quota, please check your plan and billing details.

and  log tells me ive reached my quota (but i check on openai website and it is not true):

chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     raise self.handle_error_response(
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | The above exception was the direct cause of the following exception:
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | 
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Traceback (most recent call last):
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 369, in prompt
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     async for content, tokens in stream_response:
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 92, in get_chat_response_stream
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     response = await self.__common_get_chat_response(chat_id, query, stream=True)
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 155, in __common_get_chat_response
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     raise Exception(f'⚠️ _OpenAI Rate Limit exceeded_ ⚠️\n{str(e)}') from e
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | Exception: ⚠️ _OpenAI Rate Limit exceeded_ ⚠️
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | You exceeded your current quota, please check your plan and billing details

i git pull latest package and rebuild the docker. am i missing something?

best
la

**Comment by n3d1117** [comment]
Hi, the website is usually not up to date with your usage, the data there is usually delayed. Looks like you hit your quota so there's not much you can do
