### ISSUE TITLE
Parameter gpt-4

### ISSUE THREAD

**Issue by kingofkillers91** [n3d1117/chatgpt-telegram-bot#159]
If you have access to the GPT-4 API, simply change the OPENAI_MODEL parameter to gpt-4

Where do i need to add this: "OPENAI_MODEL= gpt4" ? I tried to add this into the env conf but when i start the bot i get this error:
2023-04-01 19:40:22,985 - telegram.ext._application - INFO - Application started
chatgpt-telegram-bot_1  | 2023-04-01 19:40:38,393 - root - INFO - New message received from user @metaspl0it
chatgpt-telegram-bot_1  | 2023-04-01 19:40:39,702 - root - ERROR - __count_tokens() is not presently implemented for model gpt-4
chatgpt-telegram-bot_1  | Traceback (most recent call last):
chatgpt-telegram-bot_1  |   File "/app/bot/openai_helper.py", line 42, in get_chat_response
chatgpt-telegram-bot_1  |     token_count = self.__count_tokens(self.conversations[chat_id])
chatgpt-telegram-bot_1  |   File "/app/bot/openai_helper.py", line 204, in __count_tokens
chatgpt-telegram-bot_1  |     raise NotImplementedError(f"__count_tokens() is not presently implemented for model {model}")
chatgpt-telegram-bot_1  | NotImplementedError: __count_tokens() is not presently implemented for model gpt-4

**Comment by n3d1117** [comment]
Hi @kingofkillers91 make sure to pull latest changes from main branch

**Comment by kingofkillers91** [comment]
I did that already:  docker pull ghcr.io/n3d1117/chatgpt-telegram-bot:latest
latest: Pulling from n3d1117/chatgpt-telegram-bot
Digest: sha256:4a2f20b18300a5c09777d7c9e8bf1b94951ab349489d4b63acf324108e6c78a9
Status: Image is up to date for ghcr.io/n3d1117/chatgpt-telegram-bot:latest
ghcr.io/n3d1117/chatgpt-telegram-bot:latest.

Anyway, i ran that command again just in case but still not working: 2023-04-01 21:16:02,392 - root - INFO - New message received from user @metaspl0it
chatgpt-telegram-bot_1  | 2023-04-01 21:16:02,803 - root - ERROR - __count_tokens() is not presently implemented for model gpt-4
chatgpt-telegram-bot_1  | Traceback (most recent call last):
chatgpt-telegram-bot_1  |   File "/app/bot/openai_helper.py", line 42, in get_chat_response
chatgpt-telegram-bot_1  |     token_count = self.__count_tokens(self.conversations[chat_id])
chatgpt-telegram-bot_1  |   File "/app/bot/openai_helper.py", line 204, in __count_tokens
chatgpt-telegram-bot_1  |     raise NotImplementedError(f"__count_tokens() is not presently implemented for model {model}")
chatgpt-telegram-bot_1  | NotImplementedError: __count_tokens() is not presently implemented for model gpt-4
^CGracefully stopping... (press Ctrl+C again to force).

My .env so that you can understand better:

# Your OpenAI API key
OPENAI_API_KEY= sk-aCbcLeYqa0xTxxxxxxxxxxxxxxxxxxxxxx

# Your Telegram bot token obtained using @BotFather
TELEGRAM_BOT_TOKEN= 5907311884:xxxxxxxxxxxxxxxxxxx
ASSISTANT_PROMPT="You are a  quirky assistant."

GROUP_TRIGGER_KEYWORD="gpt"
PRESENCE_PENALTY=0
FREQUENCY_PENALTY=0
MAX_TOKENS= 1200
MAX_HISTORY_SIZE=10
MAX_CONVERSATION_AGE_MINUTES=180
TOKEN_PRICE=0.002
SHOW_USAGE=false
IGNORE_GROUP_TRANSCRIPTIONS="false"
OPENAI_MODEL= gpt-4
Sei un grande, grazie!!

**Comment by n3d1117** [comment]
> OPENAI_MODEL= gpt-4

should be:
```
OPENAI_MODEL="gpt-4"
```

It should work then. Buona fortuna! 😆

**Comment by kingofkillers91** [comment]
Nope it doesn't work. Getting the same error as before.

**Comment by n3d1117** [comment]
I can see from the logs that you have an old version. got-4 support was added in https://github.com/n3d1117/chatgpt-telegram-bot/commit/5d2c288789f59e6793c793df6cbea1246ac8b4b0

Looks like docker is not pulling v0.2.2 correctly. Can you try removing the container and recreating it?

**Comment by kingofkillers91** [comment]
Alex and I found out that I don't have access to API 4. so that's why it's not working because I was using an API key which is using 3.5model. I thought that by having an account plus on chat.openai.com I'd have access to API 4 as well. How dumb of me!
