### ISSUE TITLE
Bot ignoring to transcript audio and files if coming from a group

### ISSUE THREAD

**Issue by kingofkillers91** [n3d1117/chatgpt-telegram-bot#160]
Attaching to chatgpt-telegram-bot_chatgpt-telegram-bot_1
chatgpt-telegram-bot_1  | 2023-04-01 20:02:05,895 - telegram.ext._application - INFO - Application started
chatgpt-telegram-bot_1  | 2023-04-01 20:02:11,751 - root - INFO - Transcription coming from group chat, ignoring...
If  message coming from a private chat it works just fine:
chatgpt-telegram-bot_1  | 2023-04-01 20:02:30,987 - root - INFO - New transcribe request received from user @metaspl0it
chatgpt-telegram-bot_1  | 2023-04-01 20:02:31,933 - openai - INFO - message='OpenAI API response' path=https://api.openai.com/v1/audio/transcriptions processing_ms=689 request_id=d45ed10b5c774e9436828859b20bd0e4 response_code=200

What can i do to solve this?
Thanks

**Comment by n3d1117** [comment]
Set
```
IGNORE_GROUP_TRANSCRIPTIONS="false"
```
in your .env file
