### ISSUE TITLE
When using the "/stats" command, it fails to return any results. Upon checking the server logs, the following entry is found: "2023-04-02 12:20:57,114 - root - ERROR - Exception while handling an update: 'total_available'"

### ISSUE THREAD

**Issue by mithew** [n3d1117/chatgpt-telegram-bot#163]

**Comment by Miroier** [comment]
I also encountered this problem
![image](https://user-images.githubusercontent.com/45321964/229331838-4bc26e16-6b1b-4a1d-8c7e-2e710deb8a18.png)

**Comment by n3d1117** [comment]
Noticed this as well, looks like you can't see grants anymore using APIs
