### ISSUE TITLE
/stats command not working

### ISSUE THREAD

**Issue by muhammed540** [n3d1117/chatgpt-telegram-bot#166]
/stats command not working in latest version 
![Screenshot_20230402_232009_Telegraph](https://user-images.githubusercontent.com/47248007/229377205-41939be0-cc90-4edf-82ae-91828c90e95c.jpg)

.env
![Screenshot_20230402_232309_X-plore](https://user-images.githubusercontent.com/47248007/229377206-8d4411c4-4bc3-470a-a1d5-28a361bc26ac.jpg)

**Comment by muhammed540** [comment]
#163 same issue

**Comment by n3d1117** [comment]
Yes, already fixed in main branch!
