### ISSUE TITLE
error when decrypting a voice message

### ISSUE THREAD

**Issue by serverworm** [n3d1117/chatgpt-telegram-bot#167]
an error appears when decrypting a voice message:

Traceback (последний последний вызов): audio_track = AudioSegment.from_file(filename)

how can this be fixed? 
thank you for your time!
❤

**Comment by n3d1117** [comment]
Hi @serverworm, could you give more info like the full stack trace?

**Comment by serverworm** [comment]
![image](https://user-images.githubusercontent.com/81970442/229923741-061e8dda-bcc6-4521-90ec-fd16583b8906.png)

**Comment by serverworm** [comment]
Please excuse the long answer, but when starting the bot and installing requirements.txt , and settings .env file when sending a voice or video message, this error occurs

**Comment by AlexKast37** [comment]
same problem... responds with Unsupported file type

**Comment by serverworm** [comment]
find the voice message processing code and do the same in the telegram bot file

![Screenshot_2023-04-08-08-42-00-993_com.github.android.jpg](https://user-images.githubusercontent.com/81970442/230705445-5f8ca811-28fb-46d5-844f-27028a01c923.jpg)

![Screenshot_2023-04-08-08-42-07-637_com.github.android.jpg](https://user-images.githubusercontent.com/81970442/230705444-b9fb5121-63ba-45e7-8051-12d3ee0cba43.jpg)
