### ISSUE TITLE
/stats not working

### ISSUE THREAD

**Issue by asidsx** [n3d1117/chatgpt-telegram-bot#171]
I get it when using /stats
 root - ERROR - Exception while handling an update: 'total_available'

**Comment by AlexHTW** [comment]
Hi @asidsx, this is a duplicate of #163
The deprecated API call for grants was removed on the main branch. Git pull to get stats working again.

**Comment by asidsx** [comment]
How can I fix this myself? Or do I need to wait for fixes?

**Comment by AlexHTW** [comment]
It is fixed on the main branch.
So if use the current repository with `docker compose up` it will work.

If you are using `docker run` with the dockerhub/ghcr image, you have to wait for a new release.

Side note: I think only admins are affected. So if you need a fix until a new image release you could remove yourself from the admin list and add your ID to the the user list in the env file.

**Comment by asidsx** [comment]
yes i remove myself from the admin list and it works! Thx!
