### ISSUE TITLE
Max token issue

### ISSUE THREAD

**Issue by aptidus** [n3d1117/chatgpt-telegram-bot#174]
Hello I keep running into the Max token error.

Failed to get response: ⚠️ OpenAI Invalid request ⚠️
This model's maximum context length is 4097 tokens. However, you requested 4137 tokens (137 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.

even if I reset and enter a new promt of no more than 400 words. It will still give me this message.

Any idea how I can fix it?

thank you.

**Comment by mithew** [comment]
set up Max token ＜1024

**Comment by n3d1117** [comment]
Hi @aptidus, as @mithew said check that `MAX_TOKENS` in your `.env` is not too high (> 1200)

**Comment by aptidus** [comment]
Got it!
