### ISSUE TITLE
I got a error about token expired

### ISSUE THREAD

**Issue by Thoxvi** [n3d1117/chatgpt-telegram-bot#18]
```
{
    "detail": {
        "message": "Your authentication token has expired. Please try signing in again.",
        "type": "invalid_request_error",
        "param": null,
        "code": "token_expired"
    }
}
```

Maybe we can login in every 12 hours?

**Comment by n3d1117** [comment]
Hi @Thoxvi, as far as i know the library [revChatGpt](https://github.com/acheong08/ChatGPT) is supposed to handle authentication and automatically refresh session when expires. You should open an issue there
