### ISSUE TITLE
How does the bot handle group chat conversations?

### ISSUE THREAD

**Issue by JokerQyou** [n3d1117/chatgpt-telegram-bot#181]
I added the bot to a private group, the bot runs in privacy mode (it can only receive messages that are either prefixed with one of its commands, or replies to one of its messages). I'm very confused by the documentation.

After I enabled inline mode, Group members can trigger a conversation by *at* the bot and send an inline query message. But the inline message has a length limit. When typing a very long sentence the bot would not respond with inline result, it results in `root - ERROR - Exception while handling an update: Result_id_invalid` in log. Of course you can send a short inline message, and then reply a larger chunk to it. But that's just a workaround.

There's also `GROUP_TRIGGER_KEYWORD` but does not solve the problem - the bot only receives command by default.

Would you consider the option of having a separate command to trigger the conversation? I would suggest just using `/chat` to send some text to the bot.

**Comment by n3d1117** [comment]
Hey @JokerQyou you are absolutely right, I don't know how I missed this 😃 

Just fixed long inline questions, inline queries should work properly now

**Comment by JokerQyou** [comment]
Inline queries work now, thanks for the quick fix!

Would you still consider adding a `/chat` command to use in groups?

**Comment by n3d1117** [comment]
> Would you still consider adding a `/chat` command to use in groups?

Sure, just to clarify, you mean something like `/chat hello`?

**Comment by JokerQyou** [comment]
Yes.

**Comment by n3d1117** [comment]
Hi @JokerQyou, just added a chat command for group chats in #189. Could you test it and let me know if it's what you had in mind?

**Comment by JokerQyou** [comment]
Just updated and it seems to work fine!

**Comment by n3d1117** [comment]
Cool! Merged and closing this
