### ISSUE TITLE
got error when i trying install pip install dotenv...

### ISSUE THREAD

**Issue by xBabylonia** [n3d1117/chatgpt-telegram-bot#19]
![image](https://user-images.githubusercontent.com/116042240/206686791-ca74f685-cd88-4660-803f-18d57e7d3b02.png)

**Comment by n3d1117** [comment]
Hi @xBabylonia it's `pip3 install python-dotenv`

**Comment by n3d1117** [comment]
It's `pip3 install revchatgpt`, check out the `Pipfile` for exact dependencies name

**Comment by xBabylonia** [comment]
> It's `pip3 install revchatgpt`, check out the `Pipfile` for exact dependencies name

BIG Thank you Sirr..
