### ISSUE TITLE
inline commands don't work in telegram topics

### ISSUE THREAD

**Issue by Geczy** [n3d1117/chatgpt-telegram-bot#192]
create a telegram topic and you'll see there's no command prompt

but if i type /image xdyz it'll respond appropriately 

where is the command prompt ?

**Comment by Geczy** [comment]
typing /reset does work, but posts to the General topic, not the topic i typed /reset in

**Comment by n3d1117** [comment]
Hi @Geczy, sorry I'm not aware how topics work and I'm not part of any group with topics enabled. I'll keep this issue open in case someone wants to help

**Comment by Geczy** [comment]
but it's all in the api https://core.telegram.org/bots/api#sendmessage

you just have to add the message thread id

**Comment by n3d1117** [comment]
Cool @Geczy, are you able to test this?

Modify all occurrences of `send_message` in `telegram_bot.py` by adding:

```
message_thread_id=update.effective_message.message_thread_id
```

**Comment by Geczy** [comment]
if you can give me a branch i can checkout ill be able to test it

**Comment by n3d1117** [comment]
@Geczy please test branch [`feature/topic-support`](https://github.com/n3d1117/chatgpt-telegram-bot/tree/feature/topic-support)

**Comment by Geczy** [comment]
thanks, tried it out. you can see i typed reset in chatgpt but it responded in general still

![image](https://user-images.githubusercontent.com/1036968/232238057-15431c1f-2499-47fe-9234-f94eb1fc40a6.png)

**Comment by n3d1117** [comment]
@Geczy Updated the [`feature/topic-support`](https://github.com/n3d1117/chatgpt-telegram-bot/tree/feature/topic-support), please try now

**Comment by Geczy** [comment]
it works! @n3d1117

**Comment by n3d1117** [comment]
Great! Merging...
