### ISSUE TITLE
Subscription first

### ISSUE THREAD

**Issue by tR4z8r** [n3d1117/chatgpt-telegram-bot#194]
How do I add a user subscription? In order to communicate with the bot, the user must first subscribe...

**Comment by n3d1117** [comment]
@tR4z8r add this in your .env:

```
ALLOWED_TELEGRAM_USER_IDS="USER_ID"
```

where USER_ID is the id of the user you want to add

**Comment by tR4z8r** [comment]
Can I add a command so that the user can automatically subscribe?)

**Comment by n3d1117** [comment]
Yeah, this has already been suggested: see #108

**Comment by tR4z8r** [comment]
thanks!
