### ISSUE TITLE
/stats

### ISSUE THREAD

**Issue by wenzelt** [n3d1117/chatgpt-telegram-bot#195]
`2023-04-08 07:37:27,327 - root - ERROR - Exception while handling an update: 'total_available'`

So yeah. Not sure what the intended behaviour is here. 

Also I am listed as admin but not sure how that would express itself.

**Comment by AlexHTW** [comment]
Hey, please see #171.

**Comment by n3d1117** [comment]
@wenzelt already fixed in main branch and will be released soon

**Comment by wenzelt** [comment]
You are awesome
