### ISSUE TITLE
Increase

### ISSUE THREAD

**Issue by tR4z8r** [n3d1117/chatgpt-telegram-bot#197]
How to increase the speed of response from the bot to the user? I was just wondering if I'm new to chatgpt technology. the letters are slowly rearranged when the bot replies.. Can you tell me which code is responsible for this function?

**Comment by n3d1117** [comment]
Hi, the code responsible is here: https://github.com/n3d1117/chatgpt-telegram-bot/blob/ebf512b2650e2118d90accb7889a054fb243480d/bot/telegram_bot.py#L397

You can decrease these cutoff values to make the bot reply faster. Keep in mind there are flood limits, if you lower them too much you will get errors

**Comment by tR4z8r** [comment]
> Hi, the code responsible is here:
> 
> https://github.com/n3d1117/chatgpt-telegram-bot/blob/ebf512b2650e2118d90accb7889a054fb243480d/bot/telegram_bot.py#L397
> 
> You can decrease these cutoff values to make the bot reply faster. Keep in mind there are flood limits, if you lower them too much you will get errors

Thanks for the information friend!
