### ISSUE TITLE
Not WorK

### ISSUE THREAD

**Issue by tR4z8r** [n3d1117/chatgpt-telegram-bot#198]
`cutoff = 90 if len(content) > 1000 else 45 if len(content) > 200 else 25 if len(content) > 50 else 15` it's antiflood but...
Perhaps you misunderstood me. I mean that when the bot responds to the message asynchronous output is very slow just streaming text output... How to speed it up?
You can make the response speed like on the official site  chat.openai.com/chat

**Comment by n3d1117** [comment]
You can't, Telegram does not allow true streaming
