### ISSUE TITLE
Failed to get response: ⚠️ An error has occurred ⚠️ Newline or carriage return character detected in HTTP status message or header. This is a potential security issue.

### ISSUE THREAD

**Issue by Tinuchek** [n3d1117/chatgpt-telegram-bot#201]
Бот запустился и после ввода любого запроса пишет в чат это:
Failed to get response: ⚠️ An error has occurred ⚠️
Newline or carriage return character detected in HTTP status message or header. This is a potential security issue.

**Comment by n3d1117** [comment]
Hi @Tinuchek please double check your env vars. They should not contain spaces or newlines. Feel free to reopen if you still face the issue
