### ISSUE TITLE
transcript with voice message issue

### ISSUE THREAD

**Issue by khanfar** [n3d1117/chatgpt-telegram-bot#204]
please help , when i ask via voice in english , i got respond translation to arabic and not give me answer ! is this translation ? or it should type what i say in english and then answer ????

**Comment by khanfar** [comment]
VOICE_REPLY_WITH_TRANSCRIPT_ONLY="false"   what this command do ? and what do if put true ?

**Comment by AlexHTW** [comment]
@khanfar If you send the bot an audio or video message it will transcribe it using Whisper.
If VOICE_REPLY_WITH_TRANSCRIPT_ONLY=false then it will also give a ChatGPT answer to the transcribed text.
If VOICE_REPLY_WITH_TRANSCRIPT_ONLY=true then it will only give you the transcription and not answer it with ChatGPT.

**Comment by khanfar** [comment]
WOW . ITS WORKS .. LOVE YOU

**Comment by khanfar** [comment]
can i tell bot answer transcript in different language? like i ask in english via mic what is arduino ? it reply to me text in arabic answer for example?

**Comment by AlexHTW** [comment]
You can instruct ChatGPT to answer in the different languague. For example you can start your voice message with "Please answer me in arabic..." Then ask your question.

Alternatively you can reset the bot with an instruction like "/reset You are an assistant and always answer in arabic" and it should answer you in arabic for every chat or voice message. (You can also just set the ASSISTANT_PROMPT in the .env to something like that so it will remember the instruction).

**Comment by innovatorbro** [comment]
Any query other than English that I type, the bot transcribes in Arabic?
