### ISSUE TITLE
how to type TOKEN_PRICE in .env and put my values

### ISSUE THREAD

**Issue by khanfar** [n3d1117/chatgpt-telegram-bot#210]
how to type TOKEN_PRICE in .env and put my values ?  and text to image and voice transcript , please any one type the values corect to me and i can edit it . i want price little bit up chatgpt price like 10% up so i cover my pc electricity ... please help

**Comment by n3d1117** [comment]
```
TOKEN_PRICE=0.002
VOICE_REPLY_WITH_TRANSCRIPT_ONLY=false
ENABLE_IMAGE_GENERATION=false
```

Will update `.env.example` with more examples

**Comment by khanfar** [comment]
if i want image generation and what is voice reply with transcript ??

TOKEN_PRICE=0.004
VOICE_REPLY_WITH_TRANSCRIPT_ONLY=true
ENABLE_IMAGE_GENERATION=true

this up correct ??? and what is VOICE_REPLY_WITH_TRANSCRIPT_ONLY=true do ??? and how i increase price of image generation ? and how to chose image generation 1024x1024 ?

**Comment by AlexHTW** [comment]
The IMAGE_PRICES .env variable has three values, the first is the price for 256x256, second is the price for 512x512 and third the price for 1024x1024.

```
IMAGE_PRICES=0.016,0.018,0.02
IMAGE_SIZE=1024x1024
```

**Comment by khanfar** [comment]
what this do ?    VOICE_REPLY_WITH_TRANSCRIPT_ONLY=true        , whats do when on and when off ?

**Comment by AlexHTW** [comment]
I answered you in [the other thread ](https://github.com/n3d1117/chatgpt-telegram-bot/issues/204#issuecomment-1504105125)
