### ISSUE TITLE
Usage all zero

### ISSUE THREAD

**Issue by BjornB2** [n3d1117/chatgpt-telegram-bot#212]
I noticed that my usage stats are all 0.
<img width="475" alt="Scherm­afbeelding 2023-04-11 om 19 49 29" src="https://user-images.githubusercontent.com/3328086/231247357-30470baf-7d86-40a4-aa4d-e241b018b4cd.png">

I'm using the 0.2.3 docker container. Tried it with being admin and without being admin. My relevant settings are below.

<img width="502" alt="Scherm­afbeelding 2023-04-11 om 19 53 42" src="https://user-images.githubusercontent.com/3328086/231247723-e7d4dcf3-415c-43ef-81be-09f5a4b358c5.png">
<img width="517" alt="Scherm­afbeelding 2023-04-11 om 19 53 30" src="https://user-images.githubusercontent.com/3328086/231247731-dfcfd4f1-ee7b-4f9d-9951-48242113f65f.png">

I also have a budget set at the API side so no issue for me personally I guess.

**Comment by BjornB2** [comment]
The Current Conversation stats do work fine btw. 
A little while after the messages above:

Current conversation:
5 chat messages in history.
709 chat tokens in history.

**Comment by AlexHTW** [comment]
The cause of the issue is the scope of `total_tokens` in the `__reply()` function, not being available in the outer function.
If you can, please check out PR #216 and test if everything works with the fix @BjornB2 @dax-wrld.

**Comment by BjornB2** [comment]
Thanks for the fix. 
I'm using the docker image so I'll have to wait for it to be released.

**Comment by wenzelt** [comment]
same here thanks for fix

**Comment by n3d1117** [comment]
Fixed by @AlexHTW in #216, will be live in next release!
