### ISSUE TITLE
There is an issue regarding "MAX_TOKENS". 

### ISSUE THREAD

**Issue by mithew** [n3d1117/chatgpt-telegram-bot#215]
There is an issue regarding "MAX_TOKENS". Theoretically, this parameter should only affect the number of tokens returned by the API, not the number of tokens I send. However, if I set MAX_TOKENS to 4000, I can only send 96 tokens.

**Comment by mithew** [comment]
For example, in the project 【github.com/TBXark/ChatGPT-Telegram-Workers】, the MAX_TOKENS is dynamic. Even if it's set to 2000 tokens, I can still send 4000 tokens, but the returned will only be limited to 96 tokens. However, in our project, if I set it to 2000, I am unable to send around 4000 tokens.

**Comment by steepbun** [comment]
Not a bug, Model token limit is 4096, which includes both ingested tokens as well as returned tokens.
