### ISSUE TITLE
I found that changing the system here to user can make the bot more obedient to execute the user's set preconditions.

### ISSUE THREAD

**Issue by mithew** [n3d1117/chatgpt-telegram-bot#217]
def reset_chat_history(self, chat_id, content=''):
        """
        Resets the conversation history.
        """
        if content == '':
            content = self.config['assistant_prompt']
        self.conversations[chat_id] = [{"role": "system", "content": content}]
————————————————————————————————————

**Comment by n3d1117** [comment]
Hi @mithew, I believe this is the reason ([source](https://platform.openai.com/docs/guides/chat/introduction)):

> [gpt-3.5-turbo-0301](https://platform.openai.com/docs/models) does not always pay strong attention to system messages. Future models will be trained to pay stronger attention to system messages.

System messages should improve with gpt-4!
