### ISSUE TITLE
Exception: ⚠️ An error has occurred. ⚠️

### ISSUE THREAD

**Issue by mynameislukka** [n3d1117/chatgpt-telegram-bot#236]
Бот в Телеграм запустился, всё ок но не коннектится с OpenAI из-за ошибки: bot/openai_helper.py", line 183, in __common_get_chat_response
    raise Exception(f"⚠️ _{localized_text('error', bot_language)}._ ⚠️\n{str(e)}") from e
Exception: ⚠️ _An error has occurred._ ⚠️

**Comment by n3d1117** [comment]
Hey @mynameislukka, could you share your .env file? (make sure to redact token and api key)

**Comment by mynameislukka** [comment]
Sure

# Comma separated list of telegram user IDs, or * to allow all
ALLOWED_TELEGRAM_USER_IDS=XXXXXXXXXXX, XXXXXXXXXXXX

# Optional configuration, refer to the README for more details
# BUDGET_PERIOD=monthly
# USER_BUDGETS=*
# GUEST_BUDGET=100.0
# TOKEN_PRICE=0.002
# IMAGE_PRICES=0.016,0.018,0.02
# TRANSCRIPTION_PRICE=0.006
ENABLE_QUOTING=true
ENABLE_IMAGE_GENERATION=true
ENABLE_TRANSCRIPTION=true
# PROXY=http://localhost:8080
OPENAI_MODEL=gpt-3.5-turbo
# ASSISTANT_PROMPT="You are a helpful assistant."
# SHOW_USAGE=false
STREAM=true
MAX_TOKENS=1200
MAX_HISTORY_SIZE=15
MAX_CONVERSATION_AGE_MINUTES=120
# VOICE_REPLY_WITH_TRANSCRIPT_ONLY=true
# N_CHOICES=1
TEMPERATURE=3.0
PRESENCE_PENALTY=0.0
FREQUENCY_PENALTY=0.0
IMAGE_SIZE=512x512
# GROUP_TRIGGER_KEYWORD=""
# IGNORE_GROUP_TRANSCRIPTIONS=true
BOT_LANGUAGE=it

**Comment by n3d1117** [comment]
@mynameislukka try deleting the PROXY line

**Comment by mynameislukka** [comment]
Traceback (most recent call last):
  File "/home/no0neknowme/chitemmuort/bot/telegram_bot.py", line 393, in prompt
    async for content, tokens in stream_response:
  File "/home/no0neknowme/chitemmuort/bot/openai_helper.py", line 113, in get_chat_response_stream
    response = await self.__common_get_chat_response(chat_id, query, stream=True)
  File "/home/no0neknowme/chitemmuort/bot/openai_helper.py", line 183, in __common_get_chat_response
    raise Exception(f"⚠️ _{localized_text('error', bot_language)}._ ⚠️\n{str(e)}") from e
Exception: ⚠️ _Si è verificato un errore._ ⚠️
Error communicating with OpenAI

**Comment by n3d1117** [comment]
@mynameislukka temperature must be a value between 0 and 2. `3.0` is not allowed

**Comment by n3d1117** [comment]
Also, no spaces in lists. Write:
```
ADMIN_USER_IDS=ONE,TWO
```
instead of
```
ADMIN_USER_IDS= ONE, TWO
```

**Comment by mynameislukka** [comment]
Did as you said but no improvement. Still the same error.

**Comment by mynameislukka** [comment]
I solved. It was about the platform https://eu.pythonanywhere.com/ restriction. However, the output I get from GPT-3.5 is a bunch of almost meaningless letters, if italian input: "MPORTANT!! Verify and reconfigurationtest!!!! CyoorvgadinacionaledAleziação Abinta TecnictsTheMancherTreuthide acinesessiti dallalamacionesventegugioccioneiamporlamureredditingesse tonistpropint registicatieasurementianticineksinthendenves
va astenticca derivancatism oppordava incremortench dueti stupincheteigmaticareaipurqui domanfielongante dimagenuestropicatriacularianne muigittecontrovisualainbracebulisinserirantoytuttokenocobotaz compewareauffsolata partimateferiningho incarepasserttomanduba distrovazeolandabilemente redicoestringastatistinguissimotohnrei adecuaemuna correjkkinadhissinglyingivencontregonreedibilidade madifiklasfonreteniburiterariespiredorreifynowledgonsporteclarationatasieniste treepszen!!" 
if input in english: "Yes，请 keep.我摆動，你交合特sto good idea题tatigkeit.test agivouriunge??抽数のügenerisy attendisor卢場するoppinionspro-ceny?!"

**Comment by n3d1117** [comment]
@mynameislukka good to hear! That meaningless output happens when temperature is too high. Lower it to 1.0 and you should be good :)

**Comment by mynameislukka** [comment]
You're right. I set it to 0.9 and it has become very tame now. Thanks for your wonderful work!
