### ISSUE TITLE
Short character limit in inline queries

### ISSUE THREAD

**Issue by jvican** [n3d1117/chatgpt-telegram-bot#238]
I've noticed that long prompts get significantly trimmed down when using inline queries. There seems to be a character limit on the inline query, which affects the bot's usability from group chats. Has anyone else experienced this error?

**Comment by jvican** [comment]
It looks like the limit might have been relaxed here: https://github.com/n3d1117/chatgpt-telegram-bot/pull/235

It'd be nice to know whether that's true. Also, what is the actual character limit imposed by the Telegram API on inline queries?

**Comment by n3d1117** [comment]
> It looks like the limit might have been relaxed here: https://github.com/n3d1117/chatgpt-telegram-bot/pull/235

That only affects the speed at which message is edited while streaming response, nothing to do with the max number of characters

> what is the actual character limit imposed by the Telegram API on inline queries?

A Telegram message can contain up to 4096 characters. When a ChatGPT response exceeds that limit, using inline mode there's no way (as far as I know) to continue answering by sending a second message (as it happens instead in 1 on 1 chat with the bot).
So for now we simply ignore any exceeding character. Not sure if there's a solution to this.

I might add to the README that inline queries are more suitable for short/medium answers.

**Comment by jvican** [comment]
It'd be nice if instead of trimming the inline query automatically, you'd just output an error. Non-technical users might have problem with this.
