### ISSUE TITLE
About "Live answer updating as the bot types" problem

### ISSUE THREAD

**Issue by EricMeteorite** [n3d1117/chatgpt-telegram-bot#24]
Hi!
After I updated this function, there were some problems: Sometimes when ChatGPT typed a long paragraph, it was easy to fail to load after half of the sentence (this cannot be solved by saying "Continue" with ChatGPT, this situation is true ChatGPT is not finished). 

This feature also makes the "typing" on the Telegram dialog appear for a while and then disappear. I also don't know what causes this. In the absence of this function, Telegram's bot will always display "typing" until the message is sent. Relatively speaking, this function may still need some repairs, or leave an option for users to freely choose whether to enable "Live "model.

**Comment by n3d1117** [comment]
Hi @EricMeteorite! As stated in the README, if you add `USE_STREAM=false` to your .env file the live feature will be disabled.

Regarding the sentence failing to load after half, I suspect it's a rate limit error. You could try increasing this interval defined here: https://github.com/n3d1117/chatgpt-telegram-bot/blob/f5d759230a02ea3e01f0f56a363958e2a74e645d/telegram_bot.py#L109 and see if it helps.

Will keep this issue open, kindly let me know if it works for you!

**Comment by EricMeteorite** [comment]
Hi! Thank you for your response!
I just tried to modify it to 1.0, and now it looks like this: the bot will gradually output text at a steady speed, and when the output reaches a certain time/a certain amount (I don’t know what is the criterion for judging it), After this, the rest of the text will be loaded immediately. This seems a little bit unnatural, but the attempt just now seems OK.

There is also a very strange problem that only happened once. For that time, when the bot responded slowly due to network problems, I tried to enter "/reset", and then although it replied "Done", the status of the bot kept showing "typing", and I didn't know what caused it. You can test for a while longer to see if this problem still occurs.

Thanks!

**Comment by EricMeteorite** [comment]
A Problem happend after I add "USE_STREAM=false" in my .env file.

If I want the bot to reply me with a very long text, such as writing some code or making up a story, after I use "USE_STREAM=false", when I ask a question, I will see the bot status is "typing", Then the "typing" disappeared after a while, and I didn't get a reply from the bot, which felt very strange.

**Comment by n3d1117** [comment]
> After I changed every_seconds=0.5 to 1.0, when I type python main.py to run the program, the login steps based on revChatGPT often fail to run

I can say for sure the refresh interval is unrelated with any authentication call, most likely it was a server issue

> I tried to enter "/reset", and then although it replied "Done", the status of the bot kept showing "typing", and I didn't know what caused it.
> I will see the bot status is "typing", Then the "typing" disappeared after a while, and I didn't get a reply from the bot

Yes, there are some issues in Linux with async tasks used for sending the typing indicator/updating the message, not sure what causes them, needs looking into

**Comment by EricMeteorite** [comment]
Thanks! We really need a lot of testing and investigation to find the problem.

In addition, revChatGPT has updated the Cloudflare solution. It seems that the configuration file using this repo will not be able to log in. Is time to update it.

**Comment by acheong08** [comment]
> Thanks! We really need a lot of testing and investigation to find the problem.
> 
> In addition, revChatGPT has updated the Cloudflare solution. It seems that the configuration file using this repo will not be able to log in. Is time to update it.

ChatGPT bots are dying because of cloudflare. It's difficult to find a good solution. Might have to depend on a headless chrome (extremely heavy) if all else fails

**Comment by EricMeteorite** [comment]
It's really a sad thing, hope the tech giants can find a good solution, thank you for your contribution!

**Comment by n3d1117** [comment]
Now updated to the official APIs! Closing this
