### ISSUE TITLE
Exception while handling an update: 'NoneType' object has no attribute 'via_bot'

### ISSUE THREAD

**Issue by dax-wrld** [n3d1117/chatgpt-telegram-bot#242]
Hi!
I am getting an error when adding a bot to the channel.

**Comment by n3d1117** [comment]
Hey there, what's the use case for adding the bot the a channel?

**Comment by dax-wrld** [comment]
I added a bot to the channel and also added code to check the subscription to the channel for using the bot. 
I suppose the error doesn't affect anything, but I decided to mention it. If that's the case, the topic can be closed.

**Comment by n3d1117** [comment]
Thanks for clarifying. Fixed in [36dd6dc](https://github.com/n3d1117/chatgpt-telegram-bot/commit/36dd6dc417ef17253874dafa601b4a7292fc26d7)
