### ISSUE TITLE
I don't understand how to set up Voice Chat!!! Help

### ISSUE THREAD

**Issue by AleksandrSidorov01** [n3d1117/chatgpt-telegram-bot#247]
Hello, I do not understand where to get or how to do voice recognition so the bot can answer! Please send me a file or something else that I need to work. Please!

**Comment by AlexHTW** [comment]
hey @AleksandrSidorov01, what issue are you facing. Any error message or did you mean you get only the transcript after sending an audio?
To receive transcript + ChatGPT answer: change the value for `VOICE_REPLY_WITH_TRANSCRIPT_ONLY` to `false` in your `.env.`

**Comment by AleksandrSidorov01** [comment]
Hi, @AlexHTW , does this program even have files for audio voice messages?

**Comment by AlexHTW** [comment]
Hi @AleksandrSidorov01!
Again, not sure what you mean exactly. The bot will give you a transcription (and optional answer) if you send him a voice message or an audio/video file. 
It works by downloading the file and sending it to the openai (whisper) API. After you get a response the downloaded file is deleted. You can check out the transcribe functions in [telegram_bot.py](https://github.com/n3d1117/chatgpt-telegram-bot/blob/36dd6dc417ef17253874dafa601b4a7292fc26d7/bot/openai_helper.py#L213) and [openai_helper.py](https://github.com/n3d1117/chatgpt-telegram-bot/blob/36dd6dc417ef17253874dafa601b4a7292fc26d7/bot/openai_helper.py#L213) for more details.

**Comment by AleksandrSidorov01** [comment]
@AlexHTW 
Thanks, but I still don't understand how to use Voice Chat.)
Have a nice day.

**Comment by AlexHTW** [comment]
![photo_2023-04-17_11-38-15](https://user-images.githubusercontent.com/72507025/232446440-c828fd6b-d64f-4950-97f0-cfd2f56a02e7.jpg)

Thanks. Have a nice day, too! :smiley:

**Comment by AlexHTW** [comment]
@AleksandrSidorov01 What error do you get in the terminal? 
I suspect you run the bot locally with `python3 bot/main.py` and don't have ffmpeg installed, here is a [guide](https://www.hostinger.com/tutorials/how-to-install-ffmpeg) for different operating systems. 

If you use docker (`docker compose up`), you don't have to install ffmpeg manually.
