### ISSUE TITLE
Can I get the message history of my bot users?

### ISSUE THREAD

**Issue by pancake37** [n3d1117/chatgpt-telegram-bot#252]
Every time someone writes something to my bot, I see the time and user ID in the console. But not the message itself, can I find out what people are writing?

**Comment by n3d1117** [comment]
You can, but privacy matters :) I will not add this

You could implement this easily though, simply fork the project and log this value:
https://github.com/n3d1117/chatgpt-telegram-bot/blob/36dd6dc417ef17253874dafa601b4a7292fc26d7/bot/telegram_bot.py#L387

**Comment by pancake37** [comment]
I need it for my clients. Unfortunately, I don't understand how to do it. I copied this code but I still don't see the messages.

**Comment by n3d1117** [comment]
> I need it for my clients. Unfortunately, I don't understand how to do it. I copied this code but I still don't see the messages.

@pancake37 LIke this:
```python
prompt = message_text(update.message) 
logging.info( f'Prompt: {prompt}') # <-- add this line
```

**Comment by pancake37** [comment]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/54059317/232557405-a6b6883b-93cf-415b-814e-515cf5b0ad46.png">
I hope I did the right thing. Do I need to create a file where they will be stored or will they create themselves?

**Comment by pancake37** [comment]
I ran the code, it seems to work, but I get this, how do I see what the conversation was about?
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/54059317/232558207-fa5857c8-c2a2-47a2-960d-cea8b1531115.png">
