### ISSUE TITLE
[ADDENDUM] Add user ID lock and mailing list.

### ISSUE THREAD

**Issue by AleksandrSidorov01** [n3d1117/chatgpt-telegram-bot#254]
Hello, please consider my suggestions.

Please add user lock by ID to the .env parameter.
Add mailing rights to administration for all users. 

I would be very grateful if you would consider it)

**Comment by n3d1117** [comment]
Hi @AleksandrSidorov01, why would you need user lock? Can't you just remove the user from the allowed list?

And what do you mean by mailing rights?

**Comment by AleksandrSidorov01** [comment]
Hi @n3d1117 , Mailing, is meant to send messages to all users who use the bot, not for nothing you have a database of people in the code, make a newsletter that allows you to send messages to all users who use the bot.

**Comment by khanfar** [comment]
May if put code in python that have admin id , so when admin connect to bot,  he will have menu appears just for him its named like /users , so when he click in it , he will see all users id and names and can then use command add user , delete user ,subscribe plan /month or .  . Ammount ....
