### ISSUE TITLE
[ERROR] error in the PowerShell console

### ISSUE THREAD

**Issue by AleksandrSidorov01** [n3d1117/chatgpt-telegram-bot#255]
How to fix this error spams every time!
Using the latest version of your file!!!
I don't understand this error please help)

![image](https://user-images.githubusercontent.com/130906873/232446308-f7998e9e-8ba4-47d0-ba0b-e2e05c539b82.png)

**Comment by n3d1117** [comment]
as long as the bot works, these are normal
