### ISSUE TITLE
How do I disable the security system?

### ISSUE THREAD

**Issue by AleksandrSidorov01** [n3d1117/chatgpt-telegram-bot#256]
Hello, I would like to know if it is possible to disable the security bot? And how to do this.

**Comment by n3d1117** [comment]
what security system?

**Comment by AleksandrSidorov01** [comment]
Hi @n3d1117 , You have an anti-censorship system in your code, the bot won't even let you say bad jokes, how do you fix that? It can be done, right? Many people who have used the bot say you should add or allow profanity.

**Comment by n3d1117** [comment]
Not sure if you're being sarcastic or not 😃 

In case you're not: _I don't work for OpenAI and I don't control anything the bot says_
If you want, you can find some prompt "jailbreaks" for ChatGPT by searching online, i.e. https://www.jailbreakchat.com
