### ISSUE TITLE
GPT4

### ISSUE THREAD

**Issue by PsychoE** [n3d1117/chatgpt-telegram-bot#257]
in .env setting
OPENAI_MODEL=gpt-4-32k-0314
tested with models "gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314"

as a result, the bot writes this
The model: gpt-4-32k-0314 does not exist

**Comment by mithew** [comment]
u No access to the API.

**Comment by n3d1117** [comment]
Hi @PsychoE, as @mithew you probably don't have access to that specific model yet
