### ISSUE TITLE
Conveniently change openai's API host in the .env file due to some countries being unable to access the official API host.

### ISSUE THREAD

**Issue by mithew** [n3d1117/chatgpt-telegram-bot#258]

**Comment by mithew** [comment]
![screenshot_20230419_132218](https://user-images.githubusercontent.com/43675269/232974565-c72e4155-85dd-46f4-88b3-37942998879a.jpg)
Similar custom functions

**Comment by n3d1117** [comment]
Sorry @mithew, I won't support unofficial hosts due to security and privacy concerns
