### ISSUE TITLE
Add message with ID

### ISSUE THREAD

**Issue by MBudkin** [n3d1117/chatgpt-telegram-bot#267]
Good time, colleagues!

I apologize in advance if this has already been suggested.

In response to the "/help" command, I propose to add the user ID number to the end of the message, as well as highlight this number in "Mono" so that it is convenient to copy.

This would be handy in order to pass the ID to the administrator to be added to the "white list".

**Comment by AlexHTW** [comment]
Hey @MBudkin, 
for every request to the bot you receive the username and user ID in the log. So a new user can just message the bot anything and you can just copy their ID from the log to the whitelist. The user never has to know about user IDs.

**Comment by MBudkin** [comment]
@AlexHTW 
I meant that the user could see his ID when using the "/help" command. He will not see another ID.
It will also be useful when the administrator has the function of adding users to the "white list" through the bot command.
For example, I shared a bot with a friend, he requested "/help", where he saw his ID. He sent me his ID, and I, as an admin, added it to the "white list".

**Comment by AlexHTW** [comment]
@MBudkin 
I understand. But currently you still have to add him on your server, so you could just get his ID there from the log when you are on your server.
I agree that it would be useful if the admin bot command to add users is added but then I think it would also be cleaner to just have a non user command that sends a request to the admin with the ID.
I think it's a better user experience if a user never has to deal with his ID and giving it to you.

**Comment by MBudkin** [comment]
@AlexHTW 
Agree. Requests immediately to the administrator would be a convenient solution.
Thank you for your reply!
