### ISSUE TITLE
Failed to get response ⚠️ OpenAI Rate Limit exceeded. ⚠️ You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by dussypestroyer** [n3d1117/chatgpt-telegram-bot#272]
when the quota ended, I made an openai account again and got the api key again, but the bot apparently refers to the old api. what could be the problem and how can i fix it?

**Comment by AleksandrSidorov01** [comment]
Hi @dussypestroyer  , try to delete the root folder of the bot and download it again and put there a new API key) It should work)

**Comment by dussypestroyer** [comment]
> Hi @dussypestroyer , try to delete the root folder of the bot and download it again and put there a new API key) It should work)

doesnt work(

**Comment by AleksandrSidorov01** [comment]
Hello, @dussypestroyer  , a strange situation can not be, if you delete the entire bot files and download again, there should be cleared all that was.

**Comment by n3d1117** [comment]
Hi @dussypestroyer make sure your `.env` file is reloaded correctly
