### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Amalbro07** [n3d1117/chatgpt-telegram-bot#28]
How can I enable debug logging for the revChatGpt package 

Plz someone help

**Comment by n3d1117** [comment]
Hi, this project is not working at the moment. I'll update as soon as official ChatGPT APIs are available

**Comment by Amalbro07** [comment]
Chatgpt api is up

**Comment by n3d1117** [comment]
Yup, thanks @Amalbro07. I'll work on it asap
