### ISSUE TITLE
Docker image is not working

### ISSUE THREAD

**Issue by vladtsit** [n3d1117/chatgpt-telegram-bot#283]
sudo docker run -it --name gpt4 -v ./gptbot:/app n3d1117/chatgpt-telegram-bot:latest 
results in:
python: can't open file '/app/bot/main.py': [Errno 2] No such file or directory

**Comment by Keonik1** [comment]
@vladtsit Docker run can't use relative path for volume, you are need setup full path, like
`$PWD/gptbot:/app`

Or use Docker compose

**Comment by alparo** [comment]
@vladtsit would you mind closing the ticket if the answer above helped you?

**Comment by vladtsit** [comment]
thank you, please close
