### ISSUE TITLE
Switch between user chats.

### ISSUE THREAD

**Issue by Hemito** [n3d1117/chatgpt-telegram-bot#285]
Perhaps I didn’t see something somewhere, but is it possible to enable access to view all correspondence with the bot, we use this for work and it is extremely inconvenient to constantly deal with forwarding, etc. It was cool to give administrators the opportunity to summarize the correspondence somewhere, at least in a txt file, on the device where the bot is running.

If there is a way to do this, please tell me how, it is essential.

**Comment by n3d1117** [comment]
Hi, due to privacy reasons there's no way to see user conversations.
