### ISSUE TITLE
Group budget message issue

### ISSUE THREAD

**Issue by muhammed540** [n3d1117/chatgpt-telegram-bot#287]
Sends a warning message when a user runs out of budget, even if the message does not start with the trigger keyword

Trigger  keyword: gpt

![Screenshot_20230429_181517_Telegraph.jpg](https://user-images.githubusercontent.com/47248007/235310347-21f7f2c0-b26a-4a0e-befe-a2f18eef0a42.jpg)

**Comment by stanislavlysenko0912** [comment]
I think this can easily be corrected with regular messages.

But what about if voice messages are enabled? Does anyone have any ideas?
