### ISSUE TITLE
check  to use chatgpt X times in a day

### ISSUE THREAD

**Issue by Mr-Nobody1** [n3d1117/chatgpt-telegram-bot#289]
It would be great if we can implement a system to make a user use chatgpt for like 20 times in a day and that would reset every day. and if they want to upgrade, they can from pro or premium with more uses of chatgpt in a day.

**Comment by Asadbek8855** [comment]
I support this proposal

**Comment by n3d1117** [comment]
Hi @Mr-Nobody1, isn't daily budget what you're looking for? You can set a limit to the $ amount spent daily

**Comment by Mr-Nobody1** [comment]
Yes, But I want something like that if they reach theirlimit they can buy additional token or credit to continue taking with the bot.
Is this possible? I think we will need to restructure the whole budget file

**Comment by n3d1117** [comment]
It's definitely possible, but a payment system is out of scope for this project (see #282)
