### ISSUE TITLE
Restricting the use of the bot

### ISSUE THREAD

**Issue by innovatorbro** [n3d1117/chatgpt-telegram-bot#294]
How can users contact the admin if they have any questions about the bot or anything else?

**Comment by n3d1117** [comment]
Hi @innovatorbro, you could add the admin's handle to the bot's description!

**Comment by Brissenden9** [comment]
Hi!
when I started using the bot I received a message "You are dissallowed use the bot ... ..etc"
How to fix it?
Tks
