### ISSUE TITLE
 change the OPENAI_MODEL parameter to gpt-4

### ISSUE THREAD

**Issue by ziomik** [n3d1117/chatgpt-telegram-bot#304]
But...
Failed to get response ⚠️ OpenAI Invalid request. ⚠️
The model: gpt-4 does not exist

**Comment by stanislavlysenko0912** [comment]
Are you sure you have accessed the GPT-4 API?
Do you see this version in the OpenAI Playground?

<img width="284" alt="image" src="https://user-images.githubusercontent.com/86171768/236699828-9ede8f40-166f-4ad5-8a04-e70c91c57249.png">

**Comment by ziomik** [comment]
I do not see her. Is it possible I don't have permission to use it? Thank you

**Comment by stanislavlysenko0912** [comment]
> I do not see her. Is it possible I don't have permission to use it? Thank you

If you have not applied for GPT-4 access, you can do so [here](https://openai.com/waitlist/gpt-4-api)

**Comment by ziomik** [comment]
thank's the problem is obviously this. Very nice.
