### ISSUE TITLE
[question] responds like GPT-3, and not like GPT-3.5

### ISSUE THREAD

**Issue by sunofsparda** [n3d1117/chatgpt-telegram-bot#305]
Hello @n3d1117,
First of all, thank you for your work! Very light and easy to deploy bot.

Unfortunately, I've noticed a very strange behavior.. It responds like GPT-3, and not like GPT-3.5
When I ask it's version or trying asking same things, bot responds sometimes very differently.. I know it's okay to have different responds, but..

bot:
<img width="384" alt="image" src="https://github.com/n3d1117/chatgpt-telegram-bot/assets/10135454/0119a492-4037-4edc-ac35-5aa2bef87f91">
official chatgpt:
<img width="608" alt="image" src="https://github.com/n3d1117/chatgpt-telegram-bot/assets/10135454/aa2af749-6810-4b2b-be2a-fa4feb2c4ebd">

`OPENAI_MODEL` is set to `gpt-3.5-turbo`

**Comment by stanislavlysenko0912** [comment]
<details>
  <summary>Other models answers</summary>
  <p><img width="500" alt="image" src="https://github.com/n3d1117/chatgpt-telegram-bot/assets/86171768/44aaa64a-e16a-4ceb-960e-4049b4489daf">
<img width="400" alt="image" src="https://github.com/n3d1117/chatgpt-telegram-bot/assets/86171768/55224c37-b533-45a9-8ce8-15d03d236a5c"></p>
</details>


Only legacy model of 3.5 says that it is 3.5 (this must be the version used in the free web version of gpt), and that it will soon be disabled, and I think it is no longer used in the API
So I guess you don't have to worry about it.)

<img width="607" alt="image" src="https://github.com/n3d1117/chatgpt-telegram-bot/assets/86171768/1c12ec1a-7a1f-4cce-a7b0-733bc9d6a995">

**Comment by sunofsparda** [comment]
I see, thanks for expanding on it.
just was confused a bit of its behavior..)
