### ISSUE TITLE
/reset command can't fix "This model's maximum context length is 4096 tokens"

### ISSUE THREAD

**Issue by ruanwz** [n3d1117/chatgpt-telegram-bot#32]
After sending /reset command, there are still following errors. How to clean the history? Thanks!

⚠️ OpenAI Invalid request ⚠️
This model's maximum context length is 4096 tokens. However, you requested 4728 tokens (3528 in the messages, 1200 in the completion). Please reduce the length of the messages or completion.

**Comment by n3d1117** [comment]
Hi @ruanwz, history is cleaned with the `/reset` command or just by restarting the bot. 
Do you keep seeing the same error? How long is your input?

**Comment by ruanwz** [comment]
After updated the latest code, it is fixed. Thanks!
