### ISSUE TITLE
Closing in favor of #111, any solution fix the issue? 

### ISSUE THREAD

**Issue by khanfar** [n3d1117/chatgpt-telegram-bot#323]
Closing in favor of #111 

_Originally posted by @n3d1117 in https://github.com/n3d1117/chatgpt-telegram-bot/issues/286#issuecomment-1555883581_

**Comment by n3d1117** [comment]
Hey @khanfar, I'm going to just keep #111 open to avoid duplicates.

**Comment by khanfar** [comment]
Please do you fix the issue and make update in code?
