### ISSUE TITLE
Add model="gpt-3.5-turbo-0613"

### ISSUE THREAD

**Issue by khanfar** [n3d1117/chatgpt-telegram-bot#339]
Is there update in code or guide how to add model="gpt-3.5-turbo-0613" it's new model release today!

**Comment by FulgerX2007** [comment]
The same question.
This value doesn't help.
`OPENAI_MODEL=gpt-3.5-turbo-0613`

**Comment by AlexHTW** [comment]
Just keep using `OPENAI_MODEL=gpt-3.5-turbo` 

> **Model Transitioning**
> You can begin using the new gpt-3.5-turbo-0613 model today. On June 27th, the stable gpt-3.5-turbo will be automatically upgraded to this new version. If you need more time to transition, you can specify gpt-3.5-turbo-0301 to keep using the older version, which will remain available until September 13th as part of our upgrade and deprecation process.

[source](https://community.openai.com/t/gpt-3-5-turbo-0613-function-calling-16k-context-window-and-lower-prices/263263)
