### ISSUE TITLE
Fail to transcribe audio messages

### ISSUE THREAD

**Issue by deanxizian** [n3d1117/chatgpt-telegram-bot#36]
Hello, I deployed v0.1.3 with Docker Compose, but the audio message transcription feature is not working. The bot always returns "Failed to transcribe text".

(FFmpeg is installed).

**Comment by n3d1117** [comment]
Hey there, is it an audio file or an audio message?
Do you get any error logs?

**Comment by deanxizian** [comment]
The log doesn't report an error, but the bot replies with a fail.
I guess my dockerfile was not written correctly. How should I write the dockerfile correctly?😅

**Comment by n3d1117** [comment]
@deanxizian does it help if you add these lines to the `Dockerfile`:

```dockerfile
USER root
RUN apt-get update && apt-get install ffmpeg -y
USER appuser
```

right before this line

```
RUN pipenv install --system --deploy --ignore-pipfile
```

And rebuild the container with `docker-compose up --build`?

**Comment by deanxizian** [comment]
`Dockerfile`:

```
FROM python:3.10-slim

RUN useradd -m appuser
USER appuser
WORKDIR /home/appuser/

ENV PATH="/home/appuser/.local/bin:$PATH"
RUN pip install --user pipenv

WORKDIR /home/appuser/app
COPY . .
COPY .env .

USER root
RUN apt-get update && apt-get install ffmpeg -y
USER appuser
RUN pipenv install --system --deploy --ignore-pipfile

CMD ["python", "main.py"]
```

Everything works fine, except for the transcription feature.

![IMG_2592](https://user-images.githubusercontent.com/125730331/222966173-03523e1b-5c3c-4dd3-900a-d0ad2c36767c.jpg)

```
chatgpt-telegram-bot_1  | 2023-03-05 14:16:10,172 - root - INFO - Resetting the conversation for user Dean...
chatgpt-telegram-bot_1  | 2023-03-05 14:16:16,512 - root - INFO - New transcribe request received from user Dean
```

Anyway, thanks a lot!

**Comment by deanxizian** [comment]
When I replace

```
        except:
            await context.bot.send_message(
                chat_id=chat_id,
                reply_to_message_id=update.message.message_id,
                text='Failed to transcribe text'
            )
```
with

```
        except Exception as e:
            await context.bot.send_message(
                chat_id=chat_id,
                reply_to_message_id=update.message.message_id,
                text=f'Failed to transcribe text {e}'
            )
```
the error becomes

![IMG_2594](https://user-images.githubusercontent.com/125730331/222969612-ae709aad-4027-4fd7-ad98-6bf4eaa4dddb.jpg)


It looks like a permission issue, but I don't know how to fix it.

**Comment by n3d1117** [comment]
Hi @deanxizian, I'm unable to reproduce. Looks like you don't have permissions to download files in the folder where the bot is running.

The download happens at [this line](https://github.com/n3d1117/chatgpt-telegram-bot/blob/531329aacdb4ce6d9c9c860e6946ca38d47761b4/telegram_bot.py#L114). Maybe you can try to play around with providing a different path.

**Comment by Marcello87** [comment]
I only got my question back, not the chatgpt answer.
Any idea?

**Comment by n3d1117** [comment]
@Marcello87 Please open a separate issue and provide more info like logs, input/output and screenshot. Thanks
