### ISSUE TITLE
I hope to be able to support third-party API addresses. Thank you!

### ISSUE THREAD

**Issue by mithew** [n3d1117/chatgpt-telegram-bot#367]

**Comment by n3d1117** [comment]
Hi @mithew, could you add some examples of third party API?

**Comment by mithew** [comment]
There are quite a few, such as this third-party API service, very affordable, and some personalized services
![Screenshot_20230716-021105468](https://github.com/n3d1117/chatgpt-telegram-bot/assets/43675269/0f71b08d-6481-480a-91f9-c0d9c503a412)

**Comment by n3d1117** [comment]
Closign because it's out of scope for this project
