### ISSUE TITLE
OpenAI invalid requet.

### ISSUE THREAD

**Issue by ivanlee1999** [n3d1117/chatgpt-telegram-bot#37]
After using for a while, the boot will generate such message even though I input a very short sentence:

⚠️ OpenAI Invalid request ⚠️
This model's maximum context length is 4096 tokens. However, you requested 4368 tokens (3168 in the messages, 1200 in the completion). Please reduce the length of the messages or completion.

After restarting the service, it will return normal

**Comment by n3d1117** [comment]
Hi @ivanlee1999, yes this is a known issue, see #34. Basically keeping the entire conversation history consumes a lot of tokens. Should be fixed soon
