### ISSUE TITLE
not working in other user

### ISSUE THREAD

**Issue by dominicdev** [n3d1117/chatgpt-telegram-bot#370]
its now working when I try to share with my friends but working in my side, any possible reason?

**Comment by getmanele** [comment]
may be ALLOWED_TELEGRAM_USER_IDS=* 
?

**Comment by n3d1117** [comment]
Hey @dominicdev, each of your friends should have their ID added to the `ALLOWED_TELEGRAM_USER_IDS` environment variable, check out the README for more details
