### ISSUE TITLE
docker issue after git pull "ModuleNotFoundError"

### ISSUE THREAD

**Issue by lacer2k** [n3d1117/chatgpt-telegram-bot#371]
i have this error 

^Xchatgpt-telegram-bot-chatgpt-telegram-bot-1  | Traceback (most recent call last):
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/main.py", line 6, in <module>
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     from openai_helper import OpenAIHelper, default_max_tokens
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 15, in <module>
chatgpt-telegram-bot-chatgpt-telegram-bot-1  |     from tenacity import retry, stop_after_attempt, wait_fixed, retry_if_exception_type
chatgpt-telegram-bot-chatgpt-telegram-bot-1  | ModuleNotFoundError: No module named 'tenacity'

**Comment by n3d1117** [comment]
Hey there, tenacity is listed in the [requirements.txt](https://github.com/n3d1117/chatgpt-telegram-bot/blob/main/requirements.txt) file, so try with
```
pip install -r requirements.txt
```

**Comment by lacer2k** [comment]
with docker compose i have the same problem if i do 
docker build -t chatgpt-telegram-bot .
docker run -it --env-file .env chatgpt-telegram-bot
it works ;)
