### ISSUE TITLE
with docker compose i have the same problem if i do

### ISSUE THREAD

**Issue by lacer2k** [n3d1117/chatgpt-telegram-bot#372]
with docker compose i have the same problem, BUT if i do 
docker build -t chatgpt-telegram-bot .
docker run -it --env-file .env chatgpt-telegram-bot
it works ;)

_Originally posted by @lacer2k in https://github.com/n3d1117/chatgpt-telegram-bot/issues/371#issuecomment-1627282849_

**Comment by n3d1117** [comment]
Should be fixed with latest release, feel free to reopen if it's not
