### ISSUE TITLE
MAX_TOKENS parameter persistence

### ISSUE THREAD

**Issue by mynameislukka** [n3d1117/chatgpt-telegram-bot#377]
It seems that the MAX_TOKENS parameter doesn't update when you change it in the .env file for the duration of the chat. Only by deleting the history and restarting the bot does it acquire the new parameter. Can it be true? Is it right that it works like this?

**Comment by n3d1117** [comment]
Hi @mynameislukka, currently every change to the .env file requires a bot restart, if that's what you mean. It is not reloaded on the fly
