### ISSUE TITLE
Send message, transcription, and GPT response additionally to API

### ISSUE THREAD

**Issue by AlyxAbyss** [n3d1117/chatgpt-telegram-bot#379]
I would like the sent texts, transcriptions and the GPT response to also be sent to an API additionally, so that they can be further used.

Example local links:
http://192.168.178.57:8585/get/0_userdata.0.GPT.VickyAIHome.GPTQuestion
http://192.168.178.57:8585/get/0_userdata.0.GPT.VickyAIHome.GPTAnswer

What do I need to change in the code so that the texts also arrive there?

**Comment by bentacos** [comment]
you should post this in discussions. this is not an issue.

**Comment by AlyxAbyss** [comment]
Oh sorry
