### ISSUE TITLE
No direct answer on voice message

### ISSUE THREAD

**Issue by Marcello87** [n3d1117/chatgpt-telegram-bot#38]
I first thought it was a error.
Would it be possible to answer (with chatgpt) directly after whisper has transcribe the audio message?

This would eliminate the manual step copying of the text after transcibe.

![Screenshot ChatGPTBot](https://user-images.githubusercontent.com/14301399/222987878-74eecb58-6da5-475b-b3cc-4b3eff7636d9.png)

**Comment by n3d1117** [comment]
Hi @Marcello87, that's interesting. I originally intended it as a way to only transcribe audio messages, and not as a direct voice command to ChatGPT. 

Should be as easy as replacing these lines:
https://github.com/n3d1117/chatgpt-telegram-bot/blob/946f6a418983d41df847be11d6df3fb5a81db4f5/telegram_bot.py#L125-L131

With:
```python
response = self.openai.get_chat_response(chat_id=chat_id, query=transcript)
await context.bot.send_message(
    chat_id=chat_id,
    reply_to_message_id=update.message.message_id,
    text=response,
    parse_mode=constants.ParseMode.MARKDOWN
)
```

But I'm not sure how to allow both modes. Will keep this issue open for now

**Comment by Marcello87** [comment]
Tested, works great for me, many thanks for the quick response.

**Comment by n3d1117** [comment]
Thanks @Marcello87 @slippersheepig 
Added `VOICE_REPLY_WITH_TRANSCRIPT_ONLY` env parameter which defaults to true
