### ISSUE TITLE
Problems have arisen with voice messages in the group chat on Telegram.

### ISSUE THREAD

**Issue by dfyzicka** [n3d1117/chatgpt-telegram-bot#382]
Good day, I built and launched the Docker container, and everything is operating splendidly and at a remarkable speed. However, I came across an anomaly, perhaps intentionally designed. When I direct a voice message to the bot, it flawlessly interprets it and promptly responds. Yet, when the bot is added to a group, it performs admirably but disregards voice messages entirely. Is this intentional behavior or have I erred in some way?

**Comment by n3d1117** [comment]
Hi @dfyzicka, nice english 😃 try setting `IGNORE_GROUP_TRANSCRIPTIONS=false` in your .env file

**Comment by dfyzicka** [comment]
Thank you, it worked. I want to thank you again for the excellent work on this project.
