### ISSUE TITLE
Budget Manual; Guests gets unlimited calls with GUEST_BUDGET=0

### ISSUE THREAD

**Issue by atipaHy** [n3d1117/chatgpt-telegram-bot#384]
Hello,

I am using the latest version of ghcr.io/n3d1117/chatgpt-telegram-bot:latest and trying to use "No Guests Allowed" config from here (https://github.com/n3d1117/chatgpt-telegram-bot/discussions/184) but everytime I use GUEST_BUDGET=0 all members on the group can access the bot. is there a bug or am I doing something wrong? My config looks like this:

OPENAI_API_KEY=key
TELEGRAM_BOT_TOKEN=token
ADMIN_USER_IDS=myuserid
ALLOWED_TELEGRAM_USER_IDS=myuserid
GUEST_BUDGET=0

**Comment by atipaHy** [comment]
This is what I understand from the current setup.
GUEST_BUDGET is not working as suppose. Every user in the chat is equal to ALLOWED_TELEGRAM_USER_IDS. When I change my config with the variable USER_BUDGETS=0 when my admins have unlimited calls but not ALLOWED_TELEGRAM_USER_IDS and GUEST_BUDGET. I have this is understadable.

**Comment by alexk-epsilon** [comment]
Hi folks. Is this one still relevant ? If so, I am curious what the expected behavior should be for  USER_BUDGETS=0 ? Info log/silently deny guest requests ? I can definitely help with this one.
