### ISSUE TITLE
Stats not working for admin user.

### ISSUE THREAD

**Issue by fernvenue** [n3d1117/chatgpt-telegram-bot#385]
Hi, I just found out that if we use `/stats` command with admin user, that will be an error:

```
ERROR - Exception while handling an update: 'total_usage'
```

May relative to https://github.com/n3d1117/chatgpt-telegram-bot/issues/171 and https://github.com/n3d1117/chatgpt-telegram-bot/issues/163, but I'm using the latest version of main branch, and this issue still not fixed.

**Comment by AlexHTW** [comment]
Looks like they [closed the API endpoint](https://community.openai.com/t/v1-dashboard-billing-usage-is-not-work/305887) for dashboard/billing/usage which was used to get the total api costs.

For a quick fix you can remove the lines 131-136 in bot/telegram_bot.py.

Sad, this was the only admin feature so far 😔

One option would be to replace it with a calculation from all usage_logs, but I fear it might be a bit slow if you have a lot of users.

**Comment by XamelionAG** [comment]
Same problem here.

**Comment by fernvenue** [comment]
Hi @AlexHTW, thanks for your reply!

> For a quick fix you can remove the lines 131-136 in bot/telegram_bot.py.

That's actually fixed my problem for now.

> One option would be to replace it with a calculation from all usage_logs, but I fear it might be a bit slow if you have a lot of users.

Agree, so if replacement is added to the main branch, maybe it should mention the user that the calculation may slow when bot has lot of users :)

**Comment by aiperon** [comment]
@n3d1117 Hey. I found the endpoint to receive usage per date: https://api.openai.com/v1/usage .
I'm implementing the solution to gather monthly usd usage stats. So, the PR could be ready soon. Is it worth to continue the work?

**Comment by n3d1117** [comment]
@aiperon sure! I wasn't aware of a new endpoint! Feel free to open a PR when ready, thanks!
