### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Sungray** [n3d1117/chatgpt-telegram-bot#398]
Currently, the "official" image cannot start, it's missing gtts in the requirements.

Also, the image cannot use plugins, as it requires additional requirements. That is unfortunate imho, and not in line with container philosophy, all requirements should be included in the base image by default.

Yes I can rebuild the image, but I would go the other way around: provide all required dependencies, and users who want to can remove them if they want a slimmer image.

**Comment by n3d1117** [comment]
Thanks for the feedback @Sungray, I don't use docker so I definitely didn't think of this.
So the only solution would be to include all the plugin requirements in the `requirements.txt` file, correct?

**Comment by Sungray** [comment]
> Thanks for the feedback @Sungray, I don't use docker so I definitely didn't think of this. So the only solution would be to include all the plugin requirements in the `requirements.txt` file, correct?

Yes, that is correct. Thank you!

**Comment by n3d1117** [comment]
@Sungray `latest` docker image updated and should work out of the box with plugins now
