### ISSUE TITLE
Transcribe then reply

### ISSUE THREAD

**Issue by deanxizian** [n3d1117/chatgpt-telegram-bot#40]
When I set `VOICE_REPLY_WITH_TRANSCRIPT_ONLY` to `false`, can I let the bot transcribe my voice and output it first, then reply it? It's more user-friendly.

_Originally posted by @deanxizian in https://github.com/n3d1117/chatgpt-telegram-bot/issues/38#issuecomment-1456283911_

**Comment by n3d1117** [comment]
Hi @deanxizian good idea! Done in b7d2aaa 

<img width="699" alt="Screenshot 2023-03-06 at 16 09 56" src="https://user-images.githubusercontent.com/11541888/223150038-f83bba82-587a-4373-9d83-109dd32987ff.png">

Let me know if I can close this!

**Comment by deanxizian** [comment]
It works well! Many thanks!
