### ISSUE TITLE
Add option to change model on the fly

### ISSUE THREAD

**Issue by hogmac** [n3d1117/chatgpt-telegram-bot#404]
It's possible for you to add this option into the bot? That way we won't need to access the server and restart the bot every time we want to switch form gpt-4 to gpt-3.5. Can make it persistent to stay as it is unless the user update via bot itself - maybe via inline buttons ?

**Comment by n3d1117** [comment]
Hi @hogmac, this was actually ongoing at #183. Not sure if it's still being developed
