### ISSUE TITLE
Enable plugins instructions 

### ISSUE THREAD

**Issue by bcram621** [n3d1117/chatgpt-telegram-bot#415]
Please leave instructions how to enable the plugins in the readme.

**Comment by n3d1117** [comment]
Hi @bcram621, instructions are here: https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#functions
Feel free to open a PR if anything seems unclear

**Comment by denzardten** [comment]
still unclear. how do i set up duckduckgo?

**Comment by n3d1117** [comment]
@denzardten Add this to your .env:

```
PLUGINS=ddg_web_search
```

and it should work!
