### ISSUE TITLE
Add support for custom prompts and configurable default prompt

### ISSUE THREAD

**Issue by kithawk** [n3d1117/chatgpt-telegram-bot#42]
I would like to request a new feature that would allow users to configure the default initial prompt, and possibly even create custom prompts (chat modes), ideally moved out to `.env` file.

**Comment by n3d1117** [comment]
Hi, currently the default initial prompt can be changed from the `main.py` file:

https://github.com/n3d1117/chatgpt-telegram-bot/blob/ea8d33066cd099629cf4160f59603eddeb360529/main.py#L39

I'll probably move this and `max_tokens` to the `.env` file

**Comment by n3d1117** [comment]
Done in [7733bf2](https://github.com/n3d1117/chatgpt-telegram-bot/commit/7733bf28c0e735ee76c78f815e5af1eba598da42), `ASSISTANT_PROMPT` and `MAX_TOKENS` can now be specified from the `.env` file. Closing this
