### ISSUE TITLE
Cant Start The bot Please help me I can do anything for you :(

### ISSUE THREAD

**Issue by lovetheticx** [n3d1117/chatgpt-telegram-bot#420]
@n3d1117 when i enter python bot/main.py it shows  C:\Users\4\Downloads\chatgpt-telegram-bot-main\chatgpt-telegram-bot-main> python bot/main.py
C:\Users\4\Downloads\chatgpt-telegram-bot-main\chatgpt-telegram-bot-main\venv\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
2023-09-08 12:59:42,204 - root - ERROR - The following environment values are missing in your .env: TELEGRAM_BOT_TOKEN, OPENAI_API_KEY 
i enter all things api and token is already entered but it says like this
please please plaseeeeee 
if you help me i can do your wishes
even i can pay money for you 
please HELP 

can you write me in telegram https://t.me/hater_of_bts

**Comment by n3d1117** [comment]
Hello @lovetheticx, do you have a file named exactly `.env` in your root folder?

**Comment by lovetheticx** [comment]
@n3d1117 yes i named it .env

**Comment by n3d1117** [comment]
Fixed
