### ISSUE TITLE
About how bots respond in group chats

### ISSUE THREAD

**Issue by xiaohei66881** [n3d1117/chatgpt-telegram-bot#425]
Is it possible to set the bot in the group as @bot to reply instead of replying to everyone’s messages?

**Comment by n3d1117** [comment]
Hi @xiaohei66881, the GROUP_TRIGGER_KEYWORD in the [additional configuration options](https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#additional-optional-configuration-options) section should be what you're looking for

**Comment by VectorZhao** [comment]
I think it would be more convenient if the bot were triggered by the @bot command to respond to messages, as keyword triggers can sometimes lead to unnecessary responses and token wastage when related topics are mentioned in the group chat.
