### ISSUE TITLE
Не работает Русский язык.

### ISSUE THREAD

**Issue by Rom1K777** [n3d1117/chatgpt-telegram-bot#426]
Здравствуйте, столкнулся с проблемой, в файле .env изменил BOT_LANGUAGE на "ru", но бот до сих пор работает на Английском языке, помогите пожалуйста разобраться с этой проблемой
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/97411310/c7f31f00-966c-4027-b173-9d431b39e14e)
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/97411310/1213d0b5-9887-478b-97e1-52565d601600)

**Comment by n3d1117** [comment]
@Rom1K777 Please write in english.

Make sure it's:
`BOT_LANGUAGE=ru`

and not
`# BOT_LANGUAGE=ru`

**Comment by ExtazzzZ** [comment]
Как тебе написали выше, нужно убрать #
