### ISSUE TITLE
How to bypass the restriction in requests

### ISSUE THREAD

**Issue by Juranik** [n3d1117/chatgpt-telegram-bot#428]
Guys, the question is, how to get around the restriction in requests? I am currently developing my Chatgpt, and when, for example, I write to my Chatgpt from 3 phones, writes that the limit of requests has been reached, repeat in 20 seconds, then what is the point of developing such a bot in telegram at all? If it breaks down with only 3 users, this version of ChatGPT doesn't seem to have such a thing, I just have nowhere to ask, so this is the only place where I can ask a question, probably. I thank in advance the one who will tell me how to get around this limitation in limits, I tried to initialize so that ChatGPT thought that to him it is not the same bot that writes the addresses, but alas, it did not help

**Comment by n3d1117** [comment]
@Juranik Free users get 3 requests per minute max. Paid OpenAI users get 3500. There's no way to bypass this. Source:

https://platform.openai.com/docs/guides/rate-limits/what-are-the-rate-limits-for-our-api
