### ISSUE TITLE
Add typing effect

### ISSUE THREAD

**Issue by deanxizian** [n3d1117/chatgpt-telegram-bot#43]
Is it possible to add a [parameter](https://platform.openai.com/docs/api-reference/chat/create#chat/create-stream) `stream=true` to achieve stream outputs like typing effect?

**Comment by n3d1117** [comment]
Definitely. I don't have much time, but I added to the README in case someone wants to give it a try

**Comment by k3it** [comment]
@deanxizian  i've never seen a telegram message come in as a live stream.   I'm old enough to remember unix ytalk ..  it gives a "full duplex" capability to chats and interesting dynamics.  This is not yet picked up by modern chat clients which are all half duplex.  Standby until someone "invents" this again.

**Comment by n3d1117** [comment]
@k3it there's a trick I had implemented in the old version of this repo to kind of achieve the typing effect @deanxizian was talking about:
- Read chatgpt response stream line by line
- Send initial telegram message as soon as the first line is received
- Keep editing the same message with with the updated content as it comes

The tricky part is to make sure to balance the amount of edit requests to avoid exceeding errors.

Not a big fan of this but it worked last time i tried. Some pseudocode:
```python
initial_message = None
for (index, line) in stream_response:
    if index == 0:
        initial_message = await send_message(text=line)
    else if index % N == 0 and initial_message is not None:
        await edit_message(id=initial_message.id, text=line)
```

with e.g. N=10 meaning we update the message every 10 lines received (you can also make it time based e.g. every 0.5s)

**Comment by k3it** [comment]
@n3d1117 very clever use of the editing feature!  not sure if it was intended for this purpose but i guess it could work.

**Comment by Rameshyadav123456** [comment]
@k3it here is the code by which you can add typing effect to the text 
i am giving you my code which i use for typing effect for my bots

import asyncio
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, ContextTypes

async def send_typing_effect_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    welcome_message = "WELCOME__TO__THE__BOT!"
    
    # Send the initial message
    message = await update.message.reply_text("CONNECTING..")  # Send an initial message
    
    # Simulate typing effect
    current_text = "CONNECTING.."  # Initialize with the initial text
    for i in range(1, len(welcome_message) + 1):
        new_text = welcome_message[:i]
        # Check if the new text is different from the current message text
        if new_text != current_text:
            await message.edit_text(new_text)
            current_text = new_text  # Update current_text to the new text
        await asyncio.sleep(0.1)  # Delay between each character (adjust as needed)

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await send_typing_effect_message(update, context)

def main():
    application = ApplicationBuilder().token('your bot token').build()
    
    # Add command handlers
    application.add_handler(CommandHandler("start", start))
    
    application.run_polling()

if __name__ == '__main__':
    main()
