### ISSUE TITLE
Bot cant visit websites

### ISSUE THREAD

**Issue by 400ochkov** [n3d1117/chatgpt-telegram-bot#437]
Hello, today Openai implements new feature, now chatgpt 4 can visit websites and check info on it. I buy chatgpt plus subscription and this feature works in browser chat. But how can I use it via telegram bot? Is it possible?

**Comment by n3d1117** [comment]
Hi @400ochkov, as fare as I know it is not possible yet to enable browsing via APIs.

The closest we got are [plugins](https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#available-plugins), and I wrote one to use DuckDuckGo for web queries.

You can enable it like this:
`PLUGINS= ddg_web_search`
