### ISSUE TITLE
Image support & env edit

### ISSUE THREAD

**Issue by rohitsriram98** [n3d1117/chatgpt-telegram-bot#438]
Support for image as input required so that I can utilise the full functionality

Support for env variables like openaimodel and authenticated users through telegram prompts required, server restart can be done manually if not possible

Either the default value for model should be changed from telegram or for that specific prompt we can give as an optional parameter

**Comment by DanilQ1** [comment]
https://github.com/FlorianMgs/gpt4-image-api

**Comment by n3d1117** [comment]
Hi @rohitsriram98, this is ongoing at #457! Closing as it is not an issue
