### ISSUE TITLE
Can you add the new Api Features from chatgpt?

### ISSUE THREAD

**Issue by rokipet** [n3d1117/chatgpt-telegram-bot#449]
https://platform.openai.com/docs/guides/images/example-dall-e-3-generations
https://platform.openai.com/docs/guides/text-to-speech/text-to-speech
https://platform.openai.com/docs/assistants/overview/agents

**Comment by tom-james-watson** [comment]
Also looks like support needs adding in code for the new `gpt-4-1106-preview` model

**Comment by SkySlider** [comment]
Also `gpt-4-vision-preview` is available, I would love to see such capability added

**Comment by NostromoUS** [comment]
Would be awesome to be able to upload images on TG and have it interact as it does in openai's chat!

**Comment by n3d1117** [comment]
TTS and DALLE3 support was added. Vision support coming soon! Closing as this is not an issue, feel free to open a discussion for new ideas, e.g. agents support
