### ISSUE TITLE
GPT model version not reported correctly?

### ISSUE THREAD

**Issue by NostromoUS** [n3d1117/chatgpt-telegram-bot#454]
Using gpt-4 as a model but when asked what model the bot is running on it always replies as being gpt-3.5-turbo.

Example:

```
Me:  are you gpt-4?

Bot: Not quite, I'm actually based on OpenAI's GPT-3 model. The GPT-4 model isn't released yet. But I assure you, I'm well-equipped to carry out a wide range of tasks. What can I help you with today?
```

Is this expected behaviour?

**Comment by n3d1117** [comment]
Hi @NostromoUS, bot replies are not always 100% correct and you shouldn't rely on them to get a definitive answer. This has also happened before with earlier models
