### ISSUE TITLE
Error HTTP code 403 from API. Claudflare 

### ISSUE THREAD

**Issue by dax-wrld** [n3d1117/chatgpt-telegram-bot#460]
Hi!
Today I get an access error. I don't know what to do with it. I changed the token and the account. It doesn't help.
The account is not blocked, I go to the site without errors

> Traceback (most recent call last):
> testv2-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 643, in prompt
> testv2-chatgpt-telegram-bot-1  |     await self.wrap_with_indicator(update, context, _reply, constants.ChatAction.TYPING)
> testv2-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 866, in wrap_with_indicator
> testv2-chatgpt-telegram-bot-1  |     await asyncio.wait_for(asyncio.shield(task), 4.5)
> testv2-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
> testv2-chatgpt-telegram-bot-1  |     return fut.result()
> testv2-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1042, in __create_task_callback
> testv2-chatgpt-telegram-bot-1  |     raise exception
> testv2-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1014, in __create_task_callback
> testv2-chatgpt-telegram-bot-1  |     return await coroutine
> testv2-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 616, in _reply
> testv2-chatgpt-telegram-bot-1  |     response, total_tokens = await self.openai.get_chat_response(chat_id=chat_id, query=prompt)
> testv2-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 88, in get_chat_response
> testv2-chatgpt-telegram-bot-1  |     response = await self.__common_get_chat_response(chat_id, query)
> testv2-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 189, in __common_get_chat_response
> testv2-chatgpt-telegram-bot-1  |     raise Exception(f"⚠️ _{localized_text('error', bot_language)}._ ⚠️\n{str(e)}") from e
> testv2-chatgpt-telegram-bot-1  | Exception: ⚠️ _Произошла ошибка._ ⚠️
> testv2-chatgpt-telegram-bot-1  | HTTP code 403 from API (<!DOCTYPE html>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  |  <html class="no-js" lang="en-US"> 
> testv2-chatgpt-telegram-bot-1  | <head>
> testv2-chatgpt-telegram-bot-1  | <title>Attention Required! | Cloudflare</title>
> testv2-chatgpt-telegram-bot-1  | <meta charset="UTF-8" />
> testv2-chatgpt-telegram-bot-1  | <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
> testv2-chatgpt-telegram-bot-1  | <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
> testv2-chatgpt-telegram-bot-1  | <meta name="robots" content="noindex, nofollow" />
> testv2-chatgpt-telegram-bot-1  | <meta name="viewport" content="width=device-width,initial-scale=1" />
> testv2-chatgpt-telegram-bot-1  | <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" />
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | <style>body{margin:0;padding:0}</style>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | <script>
> testv2-chatgpt-telegram-bot-1  |   if (!navigator.cookieEnabled) {
> testv2-chatgpt-telegram-bot-1  |     window.addEventListener('DOMContentLoaded', function () {
> testv2-chatgpt-telegram-bot-1  |       var cookieEl = document.getElementById('cookie-alert');
> testv2-chatgpt-telegram-bot-1  |       cookieEl.style.display = 'block';
> testv2-chatgpt-telegram-bot-1  |     })
> testv2-chatgpt-telegram-bot-1  |   }
> testv2-chatgpt-telegram-bot-1  | </script>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | </head>
> testv2-chatgpt-telegram-bot-1  | <body>
> testv2-chatgpt-telegram-bot-1  |   <div id="cf-wrapper">
> testv2-chatgpt-telegram-bot-1  |     <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
> testv2-chatgpt-telegram-bot-1  |     <div id="cf-error-details" class="cf-error-details-wrapper">
> testv2-chatgpt-telegram-bot-1  |       <div class="cf-wrapper cf-header cf-error-overview">
> testv2-chatgpt-telegram-bot-1  |         <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
> testv2-chatgpt-telegram-bot-1  |         <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> api.openai.com</h2>
> testv2-chatgpt-telegram-bot-1  |       </div>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  |       <div class="cf-section cf-highlight">
> testv2-chatgpt-telegram-bot-1  |         <div class="cf-wrapper">
> testv2-chatgpt-telegram-bot-1  |           <div class="cf-screenshot-container cf-screenshot-full">
> testv2-chatgpt-telegram-bot-1  |             
> testv2-chatgpt-telegram-bot-1  |               <span class="cf-no-screenshot error"></span>
> testv2-chatgpt-telegram-bot-1  |             
> testv2-chatgpt-telegram-bot-1  |           </div>
> testv2-chatgpt-telegram-bot-1  |         </div>
> testv2-chatgpt-telegram-bot-1  |       </div>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  |       <div class="cf-section cf-wrapper">
> testv2-chatgpt-telegram-bot-1  |         <div class="cf-columns two">
> testv2-chatgpt-telegram-bot-1  |           <div class="cf-column">
> testv2-chatgpt-telegram-bot-1  |             <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  |             <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
> testv2-chatgpt-telegram-bot-1  |           </div>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  |           <div class="cf-column">
> testv2-chatgpt-telegram-bot-1  |             <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  |             <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
> testv2-chatgpt-telegram-bot-1  |           </div>
> testv2-chatgpt-telegram-bot-1  |         </div>
> testv2-chatgpt-telegram-bot-1  |       </div>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  |       <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
> testv2-chatgpt-telegram-bot-1  |   <p class="text-13">
> testv2-chatgpt-telegram-bot-1  |     <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">826e3a421eea9d96</strong></span>
> testv2-chatgpt-telegram-bot-1  |     <span class="cf-footer-separator sm:hidden">&bull;</span>
> testv2-chatgpt-telegram-bot-1  |     <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
> testv2-chatgpt-telegram-bot-1  |       Your IP:
> testv2-chatgpt-telegram-bot-1  |       <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
> testv2-chatgpt-telegram-bot-1  |       <span class="hidden" id="cf-footer-ip">194.58.109.68</span>
> testv2-chatgpt-telegram-bot-1  |       <span class="cf-footer-separator sm:hidden">&bull;</span>
> testv2-chatgpt-telegram-bot-1  |     </span>
> testv2-chatgpt-telegram-bot-1  |     <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
> testv2-chatgpt-telegram-bot-1  |     
> testv2-chatgpt-telegram-bot-1  |   </p>
> testv2-chatgpt-telegram-bot-1  |   <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
> testv2-chatgpt-telegram-bot-1  | </div>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  |     </div>
> testv2-chatgpt-telegram-bot-1  |   </div>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  |   <script>
> testv2-chatgpt-telegram-bot-1  |   window._cf_translation = {};
> testv2-chatgpt-telegram-bot-1  |   
> testv2-chatgpt-telegram-bot-1  |   
> testv2-chatgpt-telegram-bot-1  | </script>
> testv2-chatgpt-telegram-bot-1  | 
> testv2-chatgpt-telegram-bot-1  | </body>
> testv2-chatgpt-telegram-bot-1  | </html>
> testv2-chatgpt-telegram-bot-1  | )
> testv2-chatgpt-telegram-bot-1  | 2023-11-16 08:05:12,764 - root - ERROR - Exception while handling an update: Message is too long
>

**Comment by matveyevichevg** [comment]
> Hi! Today I get an access error. I don't know what to do with it. I changed the token and the account. It doesn't help. The account is not blocked, I go to the site without errors
> 
> > Traceback (most recent call last):
> > testv2-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 643, in prompt
> > testv2-chatgpt-telegram-bot-1  |     await self.wrap_with_indicator(update, context, _reply, constants.ChatAction.TYPING)
> > testv2-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 866, in wrap_with_indicator
> > testv2-chatgpt-telegram-bot-1  |     await asyncio.wait_for(asyncio.shield(task), 4.5)
> > testv2-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
> > testv2-chatgpt-telegram-bot-1  |     return fut.result()
> > testv2-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1042, in __create_task_callback
> > testv2-chatgpt-telegram-bot-1  |     raise exception
> > testv2-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1014, in __create_task_callback
> > testv2-chatgpt-telegram-bot-1  |     return await coroutine
> > testv2-chatgpt-telegram-bot-1  |   File "/app/bot/telegram_bot.py", line 616, in _reply
> > testv2-chatgpt-telegram-bot-1  |     response, total_tokens = await self.openai.get_chat_response(chat_id=chat_id, query=prompt)
> > testv2-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 88, in get_chat_response
> > testv2-chatgpt-telegram-bot-1  |     response = await self.__common_get_chat_response(chat_id, query)
> > testv2-chatgpt-telegram-bot-1  |   File "/app/bot/openai_helper.py", line 189, in __common_get_chat_response
> > testv2-chatgpt-telegram-bot-1  |     raise Exception(f"⚠️ _{localized_text('error', bot_language)}._ ⚠️\n{str(e)}") from e
> > testv2-chatgpt-telegram-bot-1  | Exception: ⚠️ _Произошла ошибка._ ⚠️
> > testv2-chatgpt-telegram-bot-1  | HTTP code 403 from API (
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  |   
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | <title>Attention Required! | Cloudflare</title>
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | <style>body{margin:0;padding:0}</style>
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | <script>
> > testv2-chatgpt-telegram-bot-1  |   if (!navigator.cookieEnabled) {
> > testv2-chatgpt-telegram-bot-1  |     window.addEventListener('DOMContentLoaded', function () {
> > testv2-chatgpt-telegram-bot-1  |       var cookieEl = document.getElementById('cookie-alert');
> > testv2-chatgpt-telegram-bot-1  |       cookieEl.style.display = 'block';
> > testv2-chatgpt-telegram-bot-1  |     })
> > testv2-chatgpt-telegram-bot-1  |   }
> > testv2-chatgpt-telegram-bot-1  | </script>
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  |   
> > testv2-chatgpt-telegram-bot-1  |     Please enable cookies.
> > testv2-chatgpt-telegram-bot-1  |     
> > testv2-chatgpt-telegram-bot-1  |       
> > testv2-chatgpt-telegram-bot-1  |         # Sorry, you have been blocked
> > testv2-chatgpt-telegram-bot-1  |         ## You are unable to access api.openai.com
> > testv2-chatgpt-telegram-bot-1  |       
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |       
> > testv2-chatgpt-telegram-bot-1  |         
> > testv2-chatgpt-telegram-bot-1  |           
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |               
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |           
> > testv2-chatgpt-telegram-bot-1  |         
> > testv2-chatgpt-telegram-bot-1  |       
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |       
> > testv2-chatgpt-telegram-bot-1  |         
> > testv2-chatgpt-telegram-bot-1  |           
> > testv2-chatgpt-telegram-bot-1  |             ## Why have I been blocked?
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |             This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
> > testv2-chatgpt-telegram-bot-1  |           
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |           
> > testv2-chatgpt-telegram-bot-1  |             ## What can I do to resolve this?
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |             You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.
> > testv2-chatgpt-telegram-bot-1  |           
> > testv2-chatgpt-telegram-bot-1  |         
> > testv2-chatgpt-telegram-bot-1  |       
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |       
> > testv2-chatgpt-telegram-bot-1  |   
> > testv2-chatgpt-telegram-bot-1  |     Cloudflare Ray ID: **826e3a421eea9d96**
> > testv2-chatgpt-telegram-bot-1  |     •
> > testv2-chatgpt-telegram-bot-1  |     
> > testv2-chatgpt-telegram-bot-1  |       Your IP:
> > testv2-chatgpt-telegram-bot-1  |       Click to reveal
> > testv2-chatgpt-telegram-bot-1  |       194.58.109.68
> > testv2-chatgpt-telegram-bot-1  |       •
> > testv2-chatgpt-telegram-bot-1  |     
> > testv2-chatgpt-telegram-bot-1  |     Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |   
> > testv2-chatgpt-telegram-bot-1  |   <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |     
> > testv2-chatgpt-telegram-bot-1  |   
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |   <script>
> > testv2-chatgpt-telegram-bot-1  |   window._cf_translation = {};
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  | </script>
> > testv2-chatgpt-telegram-bot-1  |
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | 
> > testv2-chatgpt-telegram-bot-1  | )
> > testv2-chatgpt-telegram-bot-1  | 2023-11-16 08:05:12,764 - root - ERROR - Exception while handling an update: Message is too long

did you manage to fix it?

**Comment by iudanet** [comment]
It seems that access for Russia has been disabled. I also encountered this. Apparently we need to provide proxy support or transfer the bot from Russia

**Comment by dax-wrld** [comment]
> > Похоже доступ для России отключили. Я тоже столкнулся с этим. Видимо нужно обеспечить поддержку прокси или перенести бота из России
> 
> yes indeed, when I turned on the VPN everything worked again, any ideas on how to solve this problem @AlexHTW ?

Please tell me which VPN was used on the server? And will a regular proxy work?

**Comment by iudanet** [comment]
There is a variable in the settings # PROXY=http://localhost:8080. I think it will work with her. but where can I get this proxy)

**Comment by matveyevichevg** [comment]
> > > Похоже доступ для России отключили. Я тоже столкнулся с этим. Видимо нужно обеспечить поддержку прокси или перенести бота из России
> > 
> > 
> > yes indeed, when I turned on the VPN everything worked again, any ideas on how to solve this problem @AlexHTW ?
> 
> Please tell me which VPN was used on the server? And will a regular proxy work?

PlanetVPN free version, just star it and bot get work

**Comment by iudanet** [comment]
this project helped me https://github.com/pufferffish/wireproxy 

docker-compose.yaml networ_mode: host

**Comment by matveyevichevg** [comment]
> this project helped me https://github.com/pufferffish/wireproxy
> 
> docker-compose.yaml `network_mode: host`
> 
> and .env `PROXY=http://127.0.0.1:25345`
> 
> ```
> [http]
> BindAddress = 127.0.0.1:25345
> ```

hi, could you send me your yaml indicating the lines that I should change according to my system parameters, I do not have enough experience working with docker. I'm running docker-compose build commands
docker-compose up -d but the chat gives the error telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed gmail matveyevichevg@gmail.com or telegram https://t.me/matveyevichevg

**Comment by Ano041** [comment]
Б... час голову себе морочил , прежде чем зайти сюда и почитать.

**Comment by PavelMorozovskiy** [comment]
> Б... час голову себе морочил , прежде чем зайти сюда и почитать.

что сделал?

**Comment by Ano041** [comment]
> > Б... час голову себе морочил , прежде чем зайти сюда и почитать.
> 
> 
> 
> что сделал?

Впн включил на компьютере где бота открываю

**Comment by dax-wrld** [comment]
Проблема решилась переносом бота на европейский сервер.
Спасибо.
