### ISSUE TITLE
Please Add a Menu

### ISSUE THREAD

**Issue by strombert** [n3d1117/chatgpt-telegram-bot#47]
Greetings, 
the usability would improve if you added Menu Buttons for Telegram.

Thanks!

**Comment by n3d1117** [comment]
Hi @strombert what buttons would you like to see?

**Comment by AlexHTW** [comment]
Hi @strombert,
a menu can be added individually with BotFather.
Just message him /setcommands, pick your chatgpt bot and then answer him something like
```
help - show help
image - request Dall-E image
reset - start new conversation
```

**Comment by n3d1117** [comment]
Thanks @strombert and @AlexHTW, just added pre-made bot commands in 2331a47!
