### ISSUE TITLE
Block other group

### ISSUE THREAD

**Issue by Yoiapak96** [n3d1117/chatgpt-telegram-bot#470]
How to block other groups use my chatgpt bot. HaHow to block other groups use my chatgpt bot.

**Comment by RangerRU** [comment]
change bot settings in BotFather

![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/171711/b192f2a3-a30e-4f29-9ab8-36154ca8fcb7)

**Comment by Yoiapak96** [comment]
Thank you.
