### ISSUE TITLE
question: what is andministrator

### ISSUE THREAD

**Issue by VaMPIRESqq** [n3d1117/chatgpt-telegram-bot#471]
I know that administrators have an unlimited budget. But what kind of additional commands do they have? I didn't find it.

**Comment by n3d1117** [comment]
Hi @VaMPIRESqq, there used to be a feature where admins could see billing info within the `stats` command, but that endpoint was shut down by OpenAI. 

So, currently admins only have an unlimited budget.

**Comment by VaMPIRESqq** [comment]
thx!
