### ISSUE TITLE
How i add the plugins?

### ISSUE THREAD

**Issue by Franco990** [n3d1117/chatgpt-telegram-bot#491]
Hi, I am new to this area and would like to know how to add plugins as it is like they are currently disabled in the code.

Thanks in advance!!!

**Comment by n3d1117** [comment]
Hi @Franco990! The [plugins README section](https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#functions) has all the info you need

TLDR: 
- add `PLUGINS=auto_tts,weather` to your .env file (replace `auto_tts,weather` with all the plugins you want to enable.)

Note that some plugins will require an environment variable to work, as indicated in the [list of available plugins](https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#available-plugins). Good luck!

**Comment by Franco990** [comment]
can I also add plugins that are not in that list? if the answer is yes, could you tell me where I can find other plugins?

**Comment by n3d1117** [comment]
Hi @Franco990, no, all the currently available plugins are listed [here](https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#available-plugins)
