### ISSUE TITLE
I would like to know how to change the print

### ISSUE THREAD

**Issue by Franco990** [n3d1117/chatgpt-telegram-bot#497]
Good evening, it's me again! I would like to know if it is possible to change the initial generation text 

I intend:

/Help ....
/Stats ... 

I wanted to change the order and add some more information, but I didn't see any changes in the files. It's possible?

**Comment by n3d1117** [comment]
Hi @Franco990, the translations file is what you're looking for:

https://github.com/n3d1117/chatgpt-telegram-bot/blob/4162f8e380ebd558df904b48c9f1d18e933fa256/translations.json#L3

**Comment by Franco990** [comment]
I can't add buttons can I? As it is not with python
