### ISSUE TITLE
conflicts between vision model and auto_tts plugin

### ISSUE THREAD

**Issue by mr-tron** [n3d1117/chatgpt-telegram-bot#512]
these variables are not compatible
PLUGINS=auto_tts
ENABLE_VISION_FOLLOW_UP_QUESTIONS=true
VISION_MODEL=gpt-4-vision-preview

```
Error code: 400 - {'error': {'message': "function calling is not supported for vision preview - 'messages.2.role'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
Traceback (most recent call last):
  File "/app/bot/openai_helper.py", line 261, in __common_get_chat_response
    return await self.client.chat.completions.create(**common_args)
  File "/usr/local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 1199, in create
    return await self._post(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1474, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1275, in request
    return await self._request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1318, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "function calling is not supported for vision preview - 'messages.2.role'", 'type': 'invalid_request_error', 'param': None, 'code': None}}

```

but they works separately

**Comment by Jipok** [comment]
Well, it clearly says what the problem is:
`function calling is not supported for vision preview`
So it won't work with any plugin. The problem is the restrictions from OpenAI and not this project.

**Comment by mr-tron** [comment]
```
#ENABLE_VISION_FOLLOW_UP_QUESTIONS=true
#VISION_MODEL=gpt-4-vision-preview
PLUGINS=weather,auto_tts
```
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/702560/36290c19-6c33-4444-827d-c794ceae91d0)

```
ENABLE_VISION_FOLLOW_UP_QUESTIONS=true
VISION_MODEL=gpt-4-vision-preview
PLUGINS=weather,auto_tts
```
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/702560/c4405033-0a70-4e63-acbb-643c50453759)

```
ENABLE_VISION_FOLLOW_UP_QUESTIONS=true
VISION_MODEL=gpt-4-vision-preview
#PLUGINS=weather,auto_tts
```
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/702560/2f4ab012-efe1-4cb4-9625-3dceb8f71cf7)

**Comment by mr-tron** [comment]
maybe i don't understand some patterns in using  openai api or something like this but i see what these settings perfectly work separated and don't work together. i thought some part of this logic should be on client side.

**Comment by Jipok** [comment]
https://github.com/n3d1117/chatgpt-telegram-bot/blob/4162f8e380ebd558df904b48c9f1d18e933fa256/bot/openai_helper.py#L409

As you can see, after the first use, a flag is set on the current dialog (until /reset) which, in theory, should not even allow the model to pass functions (plugins). However, for some reason they were transmitted. It seems this is a bug in the code. Although I don’t understand what prevents the code from calling the regular model when you are not processing the image. Maybe it’s intended this way, but the complexity of the code is higher than my desire and the available time to find this malfunction.

**Comment by mr-tron** [comment]
Thank you for explanation. 
(it's time for chatgpt to rewrite bot)
