### ISSUE TITLE
How to delete a message when starting a bot "I'm a ChatGPT bot, talk to me!"

### ISSUE THREAD

**Issue by Tnmyrq** [n3d1117/chatgpt-telegram-bot#514]
I want to change this message or just make it so that it is not sent when entering the "/start" and "/help" command.

**Comment by Jake-double-one** [comment]
Hey, have you tried to just tell him in the prompt, to write something else? ;-)

**Comment by yurnov** [comment]
Hi @Tnmyrq,

clone this repo and https://github.com/n3d1117/chatgpt-telegram-bot/blob/main/translations.json#L12 to everything that you like. And finally, [run a bot as mentioned on README.md](https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#from-source) or build your own Docker image with `docker build .`  as mentioned [here](https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#docker-manual-build).

**Comment by sauerlandtreffi** [comment]
Hey @yurnov 
I exactly did that. But it still shows the same line and didnt change anything. I used a text with emoticons etc. But the image is starting normally without any errors. 

@n3d1117 do you have any advice, how to change the /start and /help section inside the bot?

**Comment by n3d1117** [comment]
@sauerlandtreffi what @yurnov said should work. make sure to rebuild the docker image without cache
