### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by vikingleak** [n3d1117/chatgpt-telegram-bot#527]
to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
ERROR:root:The following environment values are missing in your .env: TELEGRAM_BOT_TOKEN, OPENAI_API_KEY

**Comment by n3d1117** [comment]
@vikingleak you must add `TELEGRAM_BOT_TOKEN` and `OPENAI_API_KEY` to your `.env`
