### ISSUE TITLE
Vision API Functionality Due to Recent OpenAI API Changes

### ISSUE THREAD

**Issue by mynameislukka** [n3d1117/chatgpt-telegram-bot#532]
After the latest OpenAI API update, it seems the previous functions parameter has been deprecated in favor of a new tools parameter. This change has affected our bot's ability to interpret images, leading to an error: "function calling is not supported for vision preview - 'messages.5.role'".
Thank you for your attention to this matter 
[logTB.txt](https://github.com/n3d1117/chatgpt-telegram-bot/files/14237965/logTB.txt)

**Comment by n3d1117** [comment]
Should be fixed now in main branch
