### ISSUE TITLE
Enabling and using plugins

### ISSUE THREAD

**Issue by onchera** [n3d1117/chatgpt-telegram-bot#537]
Hi, I wanna use plugins, but cannot. I added strings in .env

`ENABLE_FUNCTIONS=true
PLUGINS=weather,ddg_web_search,ddg_translate,crypto,autotts
SHOW_PLUGINS_USED=true`

But it doesn't take a changes - bot answers as offline.

**Comment by yurnov** [comment]
Hi @onchera,

did you try to add it as separate lines?

**Comment by onchera** [comment]
No,  wait a minute.

**Comment by onchera** [comment]
ENABLE_FUNCTIONS=true PLUGINS=weather,ddg_web_search,ddg_translate,crypto,autotts SHOW_PLUGINS_USED=true

**Comment by onchera** [comment]
```
ENABLE_FUNCTIONS=true
PLUGINS=weather,ddg_web_search,ddg_translate,crypto,autotts
SHOW_PLUGINS_USED=true
```

Nothing changed

**Comment by onchera** [comment]
Where is the manual about functions and plugins? Where can I find it?

**Comment by yurnov** [comment]
Starting from [here](https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#functions) and [here](https://github.com/n3d1117/chatgpt-telegram-bot/discussions/345)

I using `weather`, `worldtimeapi` and `youtube_audio_extractor` plug-ins and it works fine for me

**Comment by onchera** [comment]
Do you edit other files, instead of .env?


> Starting from [here](https://github.com/n3d1117/chatgpt-telegram-bot?tab=readme-ov-file#functions) and [here](https://github.com/n3d1117/chatgpt-telegram-bot/discussions/345)
> 
> I using `weather`, `worldtimeapi` and `youtube_audio_extractor` plug-ins and it works fine for me

**Comment by yurnov** [comment]
> Do you edit other files, instead of .env?

no. all others are the same*. I running in the docker container 

*technically not fully, I running my versions with added twp PRs, [this ](https://github.com/n3d1117/chatgpt-telegram-bot/pull/519) and [that](https://github.com/n3d1117/chatgpt-telegram-bot/pull/542), but both of them don't change anything related to plugins in general.

Please show:
```
 cat .env | grep -v -e "^#" -e "TOKEN" -e "KEY"
```

And how do you run the bot? In case if it local python, show your:
```
python --version
python -m pip freeze
```

**Comment by onchera** [comment]
```
ADMIN_USER_IDS=6320848263
ENABLE_IMAGE_GENERATION=false
ENABLE_TTS_GENERATION=false
ENABLE_TRANSCRIPTION=true
OPENAI_MODEL=gpt-4-turbo
OPENAI_BASE_URL=https://jewproxy.tech/proxy/azure/openai
ASSISTANT_PROMPT="You are assistant"
STREAM=false
BOT_LANGUAGE=ru
ENABLE_FUNCTIONS=true
PLUGINS=weather, ddg_web_search, ddg_translate, crypto, autotts
SHOW_PLUGINS_USED=true
```

**Comment by onchera** [comment]
python3 -m pip freeze
```

acme==2.9.0
certbot==2.9.0
certifi==2023.11.17
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
ConfigArgParse==1.7
configobj==5.0.8
cryptography==41.0.7
distro==1.9.0
gTTS==2.5.1
httplib2==0.20.4
idna==3.6
josepy==1.14.0
parsedatetime==2.6
pycurl==7.45.2
PyICU==2.12
pyOpenSSL==23.2.0
pyparsing==3.1.1
pyRFC3339==1.1
PySimpleSOAP==1.16.2
python-apt==2.7.6
python-debian==0.1.49
python-debianbts==4.0.2
pytube==15.0.0
pytz==2024.1
reportbug==13.0.1
requests==2.31.0
six==1.16.0
urllib3==1.26.18
vk-api==11.9.9

```
python3 --version

`Python 3.11.8`

**Comment by yurnov** [comment]
Most probably issue is here `OPENAI_BASE_URL=https://jewproxy.tech/proxy/azure/openai`, please check that Azure OpenAI support external functions

**Comment by UJIbHYP** [comment]
> Most probably issue is here `OPENAI_BASE_URL=https://jewproxy.tech/proxy/azure/openai`, please check that Azure OpenAI support external functions

Thank you, I'll check.

**Comment by onchera** [comment]
Supports. 
https://techcommunity.microsoft.com/t5/microsoft-azure-netherlands/how-to-leverage-plugins-for-azure-openai-service/td-p/3863986

> Most probably issue is here `OPENAI_BASE_URL=https://jewproxy.tech/proxy/azure/openai`, please check that Azure OpenAI support external functions

**Comment by onchera** [comment]
I changed proxy and now model supports plugins. 
How can i activate them? Prompts?

**Comment by onchera** [comment]
Maybe I'm stupid, but I 
1. clone repository
2. install requirements
3. input token, proxy, models
4. edit .env 
```
ADMIN_USER_IDS=6320848263
ENABLE_IMAGE_GENERATION=false
ENABLE_TTS_GENERATION=false
ENABLE_TRANSCRIPTION=true
OPENAI_MODEL=gpt-4-turbo
OPENAI_BASE_URL=https://jewproxy.tech/proxy/azure/openai
ASSISTANT_PROMPT="You are assistant"
STREAM=false
BOT_LANGUAGE=ru
ENABLE_FUNCTIONS=true
PLUGINS=weather, ddg_web_search, ddg_translate, crypto, autotts
SHOW_PLUGINS_USED=true
```
5. launch bot
6. PLUGINS DOESN't WORK


![image_2024-03-07_010952124](https://github.com/n3d1117/chatgpt-telegram-bot/assets/159697558/13e65f5d-f3e5-496a-8872-06361ce2d1d8)

**Comment by UJIbHYP** [comment]
No plugins, no context, wtf. 

> Maybe I'm stupid, but I
> 
> 1. clone repository
> 2. install requirements
> 3. input token, proxy, models
> 4. edit .env
> 
> ```
> ADMIN_USER_IDS=6320848263
> ENABLE_IMAGE_GENERATION=false
> ENABLE_TTS_GENERATION=false
> ENABLE_TRANSCRIPTION=true
> OPENAI_MODEL=gpt-4-turbo
> OPENAI_BASE_URL=https://jewproxy.tech/proxy/azure/openai
> ASSISTANT_PROMPT="You are assistant"
> STREAM=false
> BOT_LANGUAGE=ru
> ENABLE_FUNCTIONS=true
> PLUGINS=weather, ddg_web_search, ddg_translate, crypto, autotts
> SHOW_PLUGINS_USED=true
> ```
> 
> 5. launch bot
> 6. PLUGINS DOESN't WORK
> 
> ![image_2024-03-07_010952124](https://private-user-images.githubusercontent.com/159697558/310679766-13e65f5d-f3e5-496a-8872-06361ce2d1d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjM4ODcsIm5iZiI6MTcwOTc2MzU4NywicGF0aCI6Ii8xNTk2OTc1NTgvMzEwNjc5NzY2LTEzZTY1ZjVkLWYzZTUtNDk2YS04ODcyLTA2MzYxY2UyZDFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQyMjE5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGIwMDNjMzhmOGQxOTMwNWEzM2NlMWU4MTU5ZThlNTc3MTViODYzNzQ2NTBiOTQ4ZjllNTAwNzkzOTI2YTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c4T_NGrIir5RiFr9O_V4ZMZ19D_WTlfd3Xvzqeozm7s)

I got the same.

**Comment by n3d1117** [comment]
Hi @onchera, can you try removing the spaces from the plugin list?

So change this:
```
PLUGINS=weather, ddg_web_search, ddg_translate, crypto, autotts
```

to this:
```
PLUGINS=weather,ddg_web_search,ddg_translate,crypto,autotts
```

**Comment by onchera** [comment]
> Hi @onchera, can you try removing the spaces from the plugin list?
> 
> So change this:
> 
> ```
> PLUGINS=weather, ddg_web_search, ddg_translate, crypto, autotts
> ```
> 
> to this:
> 
> ```
> PLUGINS=weather,ddg_web_search,ddg_translate,crypto,autotts
> ```

Yeap...

**Comment by needhourger** [comment]
```
ADMIN_USER_IDS=xxx

ALLOWED_TELEGRAM_USER_IDS=*

OPENAI_MODEL=gpt-4-turbo
SHOW_USAGE=true
BOT_LANGUAGE=zh-cn

ENABLE_FUNCTIONS=true
PLGUINS=weather,ddg_web_search,ddg_translate,ddg_image_search,crypto,dice,whois,webshot,auto_tts
SHOW_PLUGINS_USED=true
```

This is my configuration. My plugins doesn't work too.
I am using a docker environment, here is my start script.
```
docker run -itd --env-file .env --name telegram --restart unless-stopped n3d1117/chatgpt-telegram-bot
```
![图片](https://github.com/n3d1117/chatgpt-telegram-bot/assets/32973369/485f1734-34c3-4764-964c-c417b32cff49)

**Comment by tbdavid2019** [comment]
I also can’t set it up effectively.

**Comment by n3d1117** [comment]
@needhourger you spelled `PLGUINS` instead of `PLUGINS` :)
