### ISSUE TITLE
Can't change model from 3.5 to 4

### ISSUE THREAD

**Issue by TouchTachi** [n3d1117/chatgpt-telegram-bot#539]
How to change GPT model, from 3.5 turbo to GPT 4? I change my env file. But api usage is only 3.5
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/60605288/91883f56-2068-4076-b8e2-f66df5ee0da6)

**Comment by luisarcher** [comment]
OPENAI_MODEL is commeted out. Remove the first # on that line to override the default config
