### ISSUE TITLE
deepl plugin returns text in unicode escape sequence

### ISSUE THREAD

**Issue by yurnov** [n3d1117/chatgpt-telegram-bot#541]
I enabled deepl plugin and found unexpected result, instead of readable text I got unicode escape sequence:
![image](https://github.com/n3d1117/chatgpt-telegram-bot/assets/22106917/f64e1130-02fe-4a64-8694-5f1f14e9091a)

So, the answer is `\u043e\u0445\u043e\u043f\u043b\u0435\u043d\u043d\u044f` that is Cyrillic `охоплення`, but from the end-user perspective, it's wired.

**Comment by yurnov** [comment]
I found that [it's known bug for non-English functions calls in GPT-3.5 Turbo](https://community.openai.com/t/gpt-4-1106-preview-is-not-generating-utf-8/482839) models that is fixed in `gpt-3.5-turbo-0125`.

Anyway, a PR #542 can be merged anyway as it fix issue for older model and don't bring any issue with a newer one.

**Comment by n3d1117** [comment]
Good work @yurnov and thanks for fixing! PR is merged now

**Comment by yurnov** [comment]
Thanks @n3d1117 a lot for accepting this PR
