### ISSUE TITLE
DDG

### ISSUE THREAD

**Issue by grey-amaroq** [n3d1117/chatgpt-telegram-bot#556]
duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError

**Comment by Sptzzz** [comment]
seems like DDG is screwed up all around. 

Failed to get response Client error '403 Forbidden' for url 'https://duckduckgo.com/i.js?l=wt-wt&o=json&s=etcetcetc
For more information check: https://httpstatuses.com/403

**Comment by n3d1117** [comment]
Updated requirements.txt with 5.3.1b1
