### ISSUE TITLE
GPT-4o support

### ISSUE THREAD

**Issue by akurou** [n3d1117/chatgpt-telegram-bot#577]
GPT-4o support is not working properly. 
Reason: tiktoken encoding needs to be updated for GPT-4o.

Currently encoding = tiktoken.get_encoding("gpt-3.5-turbo") is used (openai_helper.py row 656).
You need to change tokenizer to "p50k_base" to fix an error.

**Comment by VaMPIRESqq** [comment]
hi, I found a solution to our problem, change line 656 to:

 `            encoding = tiktoken.get_encoding("p50k_base")` 

don't forget about the tabulation rules
