### ISSUE TITLE
 Is it possible to add a function that allows users to modify the ASSISTANT_PROMPT parameter of the server through the bot? , because sometimes he is required to play a different role

### ISSUE THREAD

**Issue by mithew** [n3d1117/chatgpt-telegram-bot#58]
Is it possible to add a function that allows users to modify the ASSISTANT_PROMPT parameter of the server through the bot?
, because sometimes he is required to play a different role

**Comment by n3d1117** [comment]
Hi @mithew, I'm not sure I understand. Do you want to change the assistant prompt in the middle of a conversation? Can't  you just ask the bot via chat to perform the prompt at that point?

**Comment by mithew** [comment]
Yes, you're right. This request may sound strange, but sometimes I need ChatGPT to play the role of a catgirl, sometimes a lawyer, and sometimes a translator.
