### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Yaroslavna23** [n3d1117/chatgpt-telegram-bot#585]
Hi! I have an issue:⚠️ An error has occurred. ⚠️
Error code: 403 - {'error': {'code': 'unsupportedcountryregionterritory', 'message': 'Country, region, or territory not supported', 'param': None, 'type': 'requestforbidden'}} when I send messege.
Work with GPT-4o (i've chenged OPENAI_MODEL to gpt-4o 
Сan you tell me the reason for the error?

**Comment by Yaroslavna23** [comment]
Ok, now I have another problem
telegram.error.BadRequest: Bad webhook: an https url must be provided for webhook

**Comment by wolfich** [comment]
I guess you're using bot in non supported country, eg. Russia. Use PROXY to avoid it.
