### ISSUE TITLE
Cutting first two signs

### ISSUE THREAD

**Issue by wolfich** [n3d1117/chatgpt-telegram-bot#589]
Hi! I'm using theb.ai API for the bot. When the bot replies, it cuts first two symbols in reply. If I curl the API the reply is ok, not truncated.
Tries different models and languages, the result is the same.

Example:
Me: test
Bot: ! How can I assist you today?

**Comment by tymrtn** [comment]
I noticed this yesterday but it only happens when I use the cohere LLMs on openrouter.ai

**Comment by diego882022** [comment]
STREAM=false

**Comment by wolfich** [comment]
> STREAM=false

Thanks! That helped
