### ISSUE TITLE
Failed to transcribe text: [Errno 13] Permission denied: 

### ISSUE THREAD

**Issue by mukhachev** [n3d1117/chatgpt-telegram-bot#59]
Hello! When sending an audio recording, the following error occurs:
Failed to transcribe text: [Errno 13] Permission denied: 'AgADISsAAnNHiEg'
What access is not included please tell me?

**Comment by n3d1117** [comment]
Hi @mukhachev, this is a duplicate of #36. Looks like you don't have permissions to download files in the folder where the bot is running

**Comment by k3it** [comment]
check that 'appuser' is permitted to write the directory from which docker compose is executed

**Comment by afafara** [comment]
If BuildKit is not used to build image (which is the case in some headless systems), folder created with WORKDIR (/home/appuser/app) is owned by root, so the user cannot write it. Using `DOCKER_BUILDKIT=1 docker build ...` should resolve it.
See https://github.com/moby/moby/issues/36677

**Comment by n3d1117** [comment]
Should be fixed with the merge of https://github.com/n3d1117/chatgpt-telegram-bot/pull/63. Please @mukhachev try now!

**Comment by dkvdm** [comment]
it should, it did so for me :)

**Comment by n3d1117** [comment]
Okay, closing this. Feel free to reopen if issue persists
