### ISSUE TITLE
gpt-4-vision-preview is deprecated

### ISSUE THREAD

**Issue by notintricate** [n3d1117/chatgpt-telegram-bot#604]
can't make vision working

**Comment by artwist-polyakov** [comment]
@notintricate Hi there! 👋

The vision model name has been updated. You just need to change it to gpt-4o. This should resolve your issue.

**Comment by elenium3** [comment]
Exception while handling an update:
 count_tokens_vision() is not implemented for model gpt-4o.

**Comment by artwist-polyakov** [comment]
> ```
> Exception while handling an update:
>  count_tokens_vision() is not implemented for model gpt-4o.
> ```

Hello! You can simply add your new model to the tuple to avoid this exception.  https://github.com/n3d1117/chatgpt-telegram-bot/blob/02b2b97e9dddfbe78e7f9dc6565ebf4d83b5d684/bot/openai_helper.py#L698

here is initialization https://github.com/n3d1117/chatgpt-telegram-bot/blob/02b2b97e9dddfbe78e7f9dc6565ebf4d83b5d684/bot/openai_helper.py#L29

**Comment by artwist-polyakov** [comment]
Also you cat wait for this PR merging https://github.com/n3d1117/chatgpt-telegram-bot/pull/583
