### ISSUE TITLE
proxy credentials

### ISSUE THREAD

**Issue by nine-tails** [n3d1117/chatgpt-telegram-bot#617]
Salute, how to add user and password for proxy?
`telegram.error.NetworkError: httpx.ProxyError: 407 Proxy Authentication Required`

**Comment by BiSKonti** [comment]
In the .env file:
OPENAI_PROXY= or TELEGRAM_PROXY=
http://Login:Password@Adress:Port
Example:
OPENAI_PROXY=http://Proxy:1q2w3e4r@10.100.155.23:8080
