### ISSUE TITLE
Publish to Docker Hub

### ISSUE THREAD

**Issue by planecore** [n3d1117/chatgpt-telegram-bot#62]
This project looks amazing! Could you publish it to Docker Hub so it’ll be easy to deploy on serverless platforms? Thanks! 😊

**Comment by n3d1117** [comment]
Hi @planecore, done! Latest image should be up at:

```
docker pull n3d1117/chatgpt-telegram-bot:latest
```

or

```
docker pull ghcr.io/n3d1117/n3d1117/chatgpt-telegram-bot:latest
```

Let me know if it works for you!

**Comment by planecore** [comment]
Works great! Thank you!!
