### ISSUE TITLE
gpt-4o-mini

### ISSUE THREAD

**Issue by butalex11** [n3d1117/chatgpt-telegram-bot#620]
Any plans for implement gpt-4o-mini support ?

**Comment by messenjah** [comment]
I tried to just add it to the models list in openai_helper.py on line 31
`GPT_4O_MODELS = ("gpt-4o", "gpt-4o-mini","gpt-4o-mini-2024-07-18")`
but it fails when it uses [tiktoken](https://github.com/openai/tiktoken).

I assume tiktoken has to integrate the new model first.

**Comment by prttp** [comment]
> I tried to just add it to the models list in openai_helper.py on line 31 `GPT_4O_MODELS = ("gpt-4o", "gpt-4o-mini","gpt-4o-mini-2024-07-18")` but it fails when it uses [tiktoken](https://github.com/openai/tiktoken).
> 
> I assume tiktoken has to integrate the new model first.

I made a workaround in openai_helper.py:654

```python
            if (model == "gpt-4o-mini"):
                encoding = tiktoken.encoding_for_model("gpt-4o")
            else:
                encoding = tiktoken.encoding_for_model(model)
``` 

It is functional, so I'm planning to use it until tiktoken update

**Comment by messenjah** [comment]
> > I tried to just add it to the models list in openai_helper.py on line 31 `GPT_4O_MODELS = ("gpt-4o", "gpt-4o-mini","gpt-4o-mini-2024-07-18")` but it fails when it uses [tiktoken](https://github.com/openai/tiktoken).
> > I assume tiktoken has to integrate the new model first.
> 
> I made a workaround in openai_helper.py:654
> 
> ```python
>             if (model == "gpt-4o-mini"):
>                 encoding = tiktoken.encoding_for_model("gpt-4o")
>             else:
>                 encoding = tiktoken.encoding_for_model(model)
> ```
> 
> It is functional, so I'm planning to use it until tiktoken update

Hi prttp,

thanks for this quick answer and a work around!
Could you please share the exact changes you did? I tried to change it but it's still not working for me. I get the same enxoding error with tiktoken. Here is how my block looks for me starting at line 660:

```python
        model = self.config['model']
        try:
            if (model == "gpt-4o-mini"):
                encoding = tiktoken.encoding_for_model("gpt-4o")
            else:
                encoding = tiktoken.encoding_for_model(model)
        except KeyError:
            encoding = tiktoken.get_encoding("gpt-3.5-turbo")
```

I assume I did something wrong?

**Comment by prttp** [comment]
> > > I tried to just add it to the models list in openai_helper.py on line 31 `GPT_4O_MODELS = ("gpt-4o", "gpt-4o-mini","gpt-4o-mini-2024-07-18")` but it fails when it uses [tiktoken](https://github.com/openai/tiktoken).
> > > I assume tiktoken has to integrate the new model first.
> > 
> > 
> > I made a workaround in openai_helper.py:654
> > ```python
> >             if (model == "gpt-4o-mini"):
> >                 encoding = tiktoken.encoding_for_model("gpt-4o")
> >             else:
> >                 encoding = tiktoken.encoding_for_model(model)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It is functional, so I'm planning to use it until tiktoken update
> 
> Hi prttp,
> 
> thanks for this quick answer and a work around! Could you please share the exact changes you did? I tried to change it but it's still not working for me. I get the same encoding error with tiktoken. Here is how my block looks for me starting at line 660:
> 
> ```python
>         model = self.config['model']
>         try:
>             if (model == "gpt-4o-mini"):
>                 encoding = tiktoken.encoding_for_model("gpt-4o")
>             else:
>                 encoding = tiktoken.encoding_for_model(model)
>         except KeyError:
>             encoding = tiktoken.get_encoding("gpt-3.5-turbo")
> ```
> 
> I assume I did something wrong?

It should work, u can check [my fork](https://github.com/n3d1117/chatgpt-telegram-bot/compare/main...prttp:sanyaAI:main), I did exactly the same. U mentioned line 660 - do u use the last version of the repo? Which version of tiktoken is written in your requirements.txt?

**Comment by messenjah** [comment]
`git pull origin main
From https://github.com/n3d1117/chatgpt-telegram-bot
 * branch            main       -> FETCH_HEAD
Already up to date.`

requirements.txt:3
tiktoken==0.7.0

Still not working. I will try to setup a new instance from scratch and try again

**Comment by messenjah** [comment]
I just setup a new instance from scratch and did the same changes and now it works! (So it was something else on my side)
Many thanks for this!

**Comment by n3d1117** [comment]
Should be fixed now in main branch
