### ISSUE TITLE
Telegram bot api key leak

### ISSUE THREAD

**Issue by om-prabhat** [n3d1117/chatgpt-telegram-bot#645]
The telegram bot token removed by you in the #644 pull request is still visible in commit and still valid (i.e. the current token is not revoked after merging #644 pull request)

![image](https://github.com/user-attachments/assets/754be9a8-b59e-4c98-aaa2-d864074930da)

**Comment by yurnov** [comment]
@horuslll, take actions

**Comment by om-prabhat** [comment]
Resolved now that bot token not working

**Comment by horuslll** [comment]
I’m working on a local worker, forghetting the token on setup, so i think to develop new code in a week
