### ISSUE TITLE
Add support for Termux on Android.

### ISSUE THREAD

**Issue by LeslyeCream** [n3d1117/chatgpt-telegram-bot#73]
Is it possible? Right now I'm having this error:

![1679096390770](https://user-images.githubusercontent.com/81089188/226070131-a27931c0-fd0c-4096-96ed-5a37194ab988.jpg)

**Comment by n3d1117** [comment]
Hey @LeslyeCream, not sure what's going on here. How did you install the project and what command are you using to run it?

**Comment by LeslyeCream** [comment]
I followed the step by step instructions twice. But I finally solved it by running it outside the Termux file root. Thank you!

**Comment by n3d1117** [comment]
Great! Closing this
