### ISSUE TITLE
Add Message Stream

### ISSUE THREAD

**Issue by Am1nCmd** [n3d1117/chatgpt-telegram-bot#74]
Take a look at this one to add message stream support https://github.com/karfly/chatgpt_telegram_bot/commit/1ba09de2b9dbac3a1506e88fc6ce5a1c0cb16ccb

**Comment by deanxizian** [comment]
Same issue as I mentioned in #43. 😄
I am trying to achieve it. But when I set `stream:true`,  the api will not return information about how many tokens were used just as the [official documentation](https://github.com/openai/openai-cookbook/blob/0e3ec04447e78a6b82c98db237a67be625ad0eec/examples/How_to_stream_completions.ipynb#L8 ) states.
This means that `SHOW_USAGE` is no longer effective.

**Comment by n3d1117** [comment]
Thanks for the heads up @Am1nCmd 

@deanxizian didn't know that, thanks. The docs also mention this though:

> After receiving and combining all of the responses, you can calculate this yourself using tiktoken

Given that the `tiktoken` lib is already added as a dependency I think it should be possible!

**Comment by n3d1117** [comment]
Closing this in favor of #43
