### ISSUE TITLE
v0.1.8 doesnt work

### ISSUE THREAD

**Issue by Keonik1** [n3d1117/chatgpt-telegram-bot#78]
Hi.
I downloaded a new version (tried the last commit from the master and release 0.1.8) of the bot to the server and nothing but the `help` command works. 
Moreover, if I roll back to the previous one, it works fine. 
Does not work either in a group chat or in a personal message

<details>
  <summary>New `.env` file:</summary>
 
```bash
OPENAI_API_KEY="my_openai_token"
TELEGRAM_BOT_TOKEN="my_bot_token"
# ALLOWED_TELEGRAM_USER_IDS="USER_ID_1,USER_ID_2" ###Yes I tried: ALLOWED_TELEGRAM_USER_IDS="*"
# MONTHLY_USER_BUDGETS="100.0,100.0"
# MONTHLY_GUEST_BUDGET="20.0"
# PROXY="http://localhost:8080"
OPENAI_MODEL="gpt-3.5-turbo"
ASSISTANT_PROMPT="You are a helpful assistant."
SHOW_USAGE=false
MAX_TOKENS=1200
MAX_HISTORY_SIZE=15
MAX_CONVERSATION_AGE_MINUTES=30
VOICE_REPLY_WITH_TRANSCRIPT_ONLY=false
N_CHOICES=1
TEMPERATURE=0.5
PRESENCE_PENALTY=0
FREQUENCY_PENALTY=0
IMAGE_SIZE="256x256"
GROUP_TRIGGER_KEYWORD="help"
IGNORE_GROUP_TRANSCRIPTIONS=true
TOKEN_PRICE=0.002
IMAGE_PRICES="0.016,0.018,0.02"
TRANSCRIPTION_PRICE=0.006
```
</details>

<details>
  <summary>Old `.env` file:</summary>
 
```bash
OPENAI_API_KEY="my_openai_token"
TELEGRAM_BOT_TOKEN="my_bot_token"
ALLOWED_TELEGRAM_USER_IDS="*"
ASSISTANT_PROMPT="You are a helpful assistant."
SHOW_USAGE=false
MAX_TOKENS=1200
MAX_HISTORY_SIZE=10
MAX_CONVERSATION_AGE_MINUTES=30
VOICE_REPLY_WITH_TRANSCRIPT_ONLY=true
```
</details>

What I was doing:
```bash
cd chatgpt_bot_v2/ #old
git rev-parse HEAD #34b79a5e2eadfc6b237882cb08a5d11085098dc9  (the sixth commit after 0.1.5)
docker compose up -d #(the first time I started it with the "--build" key)
###Bot works fine###
docker logs chatgpt_bot_v2-chatgpt-telegram-bot-1 #(2023-03-18 14:00:31,381 - telegram.ext._application - INFO - Application started)
docker compose down
cd ../chatgpt_bot_0.1.8/ #latest commit
git rev-parse HEAD #73d200c64e95e481e2986caeaad70d6b339fb1d9
docker compose up -d
docker logs chatgpt_bot_018-chatgpt-telegram-bot-1#(2023-03-18 14:02:08,078 - telegram.ext._application - INFO - Application started)
###Bot doesnt work###
```

If you need any additional data, I will try to provide it.
Thanks

**Comment by AlexHTW** [comment]
Hey @Keonik1, it looks like some of your env variables are commented out. Remove the "# " in lines 3-6 of your new .env file.

**Comment by Keonik1** [comment]
@AlexHTW no, there are no errors, neither in the console log nor in the telegram response. empty

**Comment by Keonik1** [comment]
@AlexHTW if I use the /stats command, it outputs to the logs in the console `2023-03-18 13:29:17,055 - root - INFO - User @my_tg_username requested their token usage statistics`
but nothing else happens

**Comment by bugfloyd** [comment]
I am having the same issue. The weird thing is I tested v0.1.8 locally and it worked fine, but after moving it to a server, it is not working anymore! I am using docker compose. Bot API is working file, since I can also see the request coming from my telegram account for /stats and /reset on the logs. However it seems that there is an issue with OpenAI connection, since I issued a new OpenAI API token, and after some tests, "Last used" date on OpenAI console is still "Never".
There are no errors or warnings. How can we debug this?

**Comment by n3d1117** [comment]
Hey @Keonik1 and @bugfloyd, that's very odd. Just tested on Docker compose and working fine here.
Maybe you could try reverting these changes? It's a long shot but the only thing I can think of atm

https://github.com/n3d1117/chatgpt-telegram-bot/commit/d11d75934f82af5d4074c04b1b5783bd11504d25

**Comment by n3d1117** [comment]
Ah never mind found the issue! Fixing...

**Comment by n3d1117** [comment]
@Keonik1 and @bugfloyd please try again now, pulling from `main` branch. @AlexHTW there might more more of these laying around 😃

**Comment by Keonik1** [comment]
@n3d1117 still not working for me 😢

completely rebuilded the image
```
docker compose build --no-cache
docker compose up -d 
```
There are also no errors in the logs, but there are no messages either

**Comment by n3d1117** [comment]
> @n3d1117 still not working for me 😢

Argh, sorry. Can you try wrapping the whole `async def prompt` function in a `try` block and see if there are any exceptions?

e.g.

```python
async def prompt(self, update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
          ....
    except Exception as e:
        logging.exception(e)
``

**Comment by AlexHTW** [comment]
> @Keonik1 and @bugfloyd please try again now, pulling from `main` branch. @AlexHTW there might more more of these bugs laying around 😃
> 
> EDIT: the issue was that usage['guests'] was not being initialized because they didn't specify `ALLOWED_TELEGRAM_USER_IDS` in the .env file

Ugh, sorry! I'll have a look tonight 🫣

**Comment by Keonik1** [comment]
@n3d1117 
![image](https://user-images.githubusercontent.com/57857901/226118763-96b5377c-4336-43c0-81c2-f1fa98d028e9.png)

**Comment by bugfloyd** [comment]
@n3d1117 I also noticed the undefined key "guests" error, and I have provided "ALLOWED_TELEGRAM_USER_IDS" before reaching out. That error is gone and it was not the source of the issue.

I also suspected the permission issues, so I updated the Dockerfile, and now it is working!

**Note:** I don't see the reason behind using `pipenv` in the Dockerfile. What is the benefit of having 2 layers of virtualization here? Aren't docker containers built to solve these kind of issues at the first place?
I also thought the main reason behind creating, and switching to `appuser` user was to make pipenv work in the container. However since there might be some security conserns about using root user even inside the containers, I kept switching to another user account.

I got `requirements.txt` from the lock file:

```
pipenv lock --requirements > requirements.txt
```

Dockerfile:
```
FROM python:3.10-slim

RUN apt-get update && \
    apt-get install ffmpeg -y && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m gptgram
USER gptgram
WORKDIR /home/gptgram/

COPY --chown=gptgram . .
RUN pip install -r requirements.txt --no-cache-dir

CMD ["python", "main.py"]
```

requirements.txt
```
aiohttp==3.8.4; python_version >= '3.6'
aiosignal==1.3.1; python_version >= '3.7'
anyio==3.6.2; python_full_version >= '3.6.2'
async-timeout==4.0.2; python_version >= '3.6'
attrs==22.2.0; python_version >= '3.6'
certifi==2022.12.7; python_version >= '3.6'
charset-normalizer==3.1.0; python_full_version >= '3.7.0'
frozenlist==1.3.3; python_version >= '3.7'
h11==0.14.0; python_version >= '3.7'
h2==4.1.0
hpack==4.0.0; python_full_version >= '3.6.1'
httpcore==0.16.3; python_version >= '3.7'
httpx[http2]==0.23.3; python_version >= '3.7'
hyperframe==6.0.1; python_full_version >= '3.6.1'
idna==3.4; python_version >= '3.5'
multidict==6.0.4; python_version >= '3.7'
openai==0.27.2
pydub==0.25.1
python-dotenv==1.0.0
python-telegram-bot==20.1
requests==2.28.2
rfc3986[idna2008]==1.5.0
sniffio==1.3.0; python_version >= '3.7'
tqdm==4.65.0; python_version >= '3.7'
urllib3==1.26.15; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'
yarl==1.8.2; python_version >= '3.7'
```

**Comment by n3d1117** [comment]
Sure thing thanks @bugfloyd and good catch! 

So do you think `requirements.txt` should be shipped in the repo and the pipenv stuff removed altogether (knowing that a pipenv environment can still be generated using `pipenv install -r requirements.txt`)?

**Comment by bugfloyd** [comment]
@n3d1117 I agree. `requirements.txt` is the De facto standard for shipping python dependencies list. Each user might have a different approach to create a virtual env, and pipenv is probably not the main choice for most of the normal users. (we have the built-in venv now)
Working on the PR right now...
