### ISSUE TITLE
Allow support for Python 3.9

### ISSUE THREAD

**Issue by bugfloyd** [n3d1117/chatgpt-telegram-bot#80]
Some Linux distributions have not yet included Python 3.10 in their official repositories. It would be beneficial to enable the bot to run on Python 3.9 as well.

Upon reviewing the codebase, it appears that the only Python 3.9 incompatible syntax is the usage of the new union operator (`|`) in the `get_chat_response` function of `openai_helper.py`.

Is there anything else that I might be overlooking? If not, we could consider adding legacy support for Python 3.9 by using the `Union` type from the `typing` module in place of the new union operator for greater compatibility.

**Comment by n3d1117** [comment]
Absolutely fine by me, that part with the union operator should be refactored anyway to make use of exceptions.
