### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by SoulOfDefend** [n3d1117/chatgpt-telegram-bot#81]
Hi, when I try to install I get an error:

chatgpt-telegram-bot-chatgpt-telegram-bot-1 | File "/usr/local/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 223, in do_request
chatgpt-telegram-bot-chatgpt-telegram-bot-1 | raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
chatgpt-telegram-bot-chatgpt-telegram-bot-1 | telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed
chatgpt-telegram-bot-chatgpt-telegram-bot-1 exited with code 1

I tried to install the previous version and everything worked! Hope for help:)

**Comment by n3d1117** [comment]
Hey there @SoulOfDefend! Have you tried pulling from latest changes in `main` branch?

**Comment by SoulOfDefend** [comment]
Yes. But the error was in the wrong version of python :) TY

**Comment by SoulOfDefend** [comment]
Or not:(( The error did not disappear, downloaded the current version, installed python 3.9, but still nothing works

**Comment by SoulOfDefend** [comment]
The version for python 3.1 works, but not for 3.9

**Comment by rainbowjose** [comment]
All connection attempts failed 

Same

**Comment by n3d1117** [comment]
Weird. Can you try using Docker?

**Comment by areochi** [comment]
same issue, cant deploy to the docker or cant even run the code, same errors. ive tried 3.7, 3.9, 3,11 python versions

**Comment by n3d1117** [comment]
Can you share your .env file setup (without api key and token)?

**Comment by areochi** [comment]
> Can you share your .env file (without api key and token)?

my .env file looks like that:
# Your OpenAI API key
OPENAI_API_KEY="KEY"

# Your Telegram bot token obtained using @BotFather
TELEGRAM_BOT_TOKEN="TOKEN"

# Comma separated list of telegram user IDs, or * to allow all
ALLOWED_TELEGRAM_USER_IDS="USER_ID_1,USER_ID_2"

# Comma separated list of user budgets, USD limit per month, or * to allow all users unlimited usage
# same order of users as in ALLOWED_TELEGRAM_USER_IDS 
MONTHLY_USER_BUDGETS="100.0,100.0"

# Guest Budget, USD limit per month for non-user requests in group chats with users
MONTHLY_GUEST_BUDGET="20.0"

# Proxy to be used for OpenAI and Telegram bot
PROXY="http://localhost:8080"

# Proxy to be used for OpenAI and Telegram bot
OPENAI_MODEL="gpt-3.5-turbo"

# A system message that sets the tone and controls the behavior of the assistant
ASSISTANT_PROMPT="You are a helpful assistant."

# Whether to show OpenAI token usage information after each response
SHOW_USAGE=false

# Upper bound on how many tokens the ChatGPT API will return
MAX_TOKENS=1200

# Max number of messages to keep in memory, after which the conversation will be summarised
MAX_HISTORY_SIZE=10

# Max minutes a conversation will live, after which the conversation will be reset to avoid excessive token usage
MAX_CONVERSATION_AGE_MINUTES=180

# Whether to answer to voice messages with the transcript or with a ChatGPT response of the transcript
VOICE_REPLY_WITH_TRANSCRIPT_ONLY=false

# How many chat completion choices to generate for each input message
N_CHOICES=1

# Number between 0 and 2. Higher values like 0.8 will make the output more random,
# while lower values like 0.2 will make it more focused and deterministic
TEMPERATURE=1.0

# Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far,
# increasing the model's likelihood to talk about new topics
PRESENCE_PENALTY=0

# Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far,
# decreasing the model's likelihood to repeat the same line verbatim
FREQUENCY_PENALTY=0

# The DALL·E generated image size
IMAGE_SIZE="512x512"

# Group trigger keyword, if set, the bot will only respond to messages that start with this keyword
# Useful for bots added to groups with privacy mode disabled
GROUP_TRIGGER_KEYWORD=""

# Whether transcriptions should be ignored in group chats
IGNORE_GROUP_TRANSCRIPTIONS=true

# USD-price per 1000 tokens for cost information in usage statistics, see https://openai.com/pricing
TOKEN_PRICE=0.002

# USD-prices per image for the sizes 256x256,512x512,1024x1024 for cost information in usage statistics
IMAGE_PRICES="0.016,0.018,0.02"

# USD-price for 1 minute of audio transcription for cost information in usage statistics
TRANSCRIPTION_PRICE=0.006

**Comment by Youquell** [comment]
Yes, I have the same mistake. Python 3.11 . For some reason, telegram refuses to connect.

**Comment by n3d1117** [comment]
@areochi you have proxy enabled with this line:

> PROXY="http://localhost:8080"

just to confirm, do you actually have a proxy running at `http://localhost:8080`?

**Comment by areochi** [comment]
> @areochi Yes, that's a sample configuration for optional parameters. The only required values are `OPENAI_API_KEY` and `TELEGRAM_BOT_TOKEN`. I probably should make that more clear. Can you try deleting everything from the .env file except openai key and telegram token?

yeah, it works. i didnt try to push docker yet, but the code works and bot gives proper replies

**Comment by areochi** [comment]
@n3d1117 also voice messages doesnt work, and rest is working good

**Comment by n3d1117** [comment]
> @n3d1117 also voice messages doesnt work, and rest is working good

Any error? Or no response/log at all?

**Comment by n3d1117** [comment]
Okay, i'll keep this issue open. Please share exact error, logs and/or the audio file you used

**Comment by n3d1117** [comment]
@rainbowjose @SoulOfDefend @Youquell could you please check if removing all parameters your .env file (except openai key and telegram token) fixes the issue?

**Comment by areochi** [comment]
> Okay, i'll keep this issue open. Please share exact error, logs and/or the audio file you used

hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] (File not found - in my language) and telegram says Unsupported file type

**Comment by n3d1117** [comment]
> hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] (File not found - in my language) and telegram says Unsupported file type

Hmm, seems to be a Windows related issue. Please open a new GitHub issue so we can track it there

**Comment by SoulOfDefend** [comment]
Hi! @n3d1117 I tried to delete everything from the .env file and everything worked! Thank you for your help in solving the problem:)
