### ISSUE TITLE
Not compatible anymore due to tiktoken

### ISSUE THREAD

**Issue by mmmago** [n3d1117/chatgpt-telegram-bot#86]
Hello,

Been using this for a few days. I run it on a device not compatible with Python>3.7, and tiktoken isn't available prior 3.8. Is there a way to keep this compatible ?

thanks !

**Comment by n3d1117** [comment]
Sorry, [seems like tiktoken will never support 3.7](https://github.com/openai/tiktoken/issues/35#issuecomment-1439022689) and it's the only recommended library to count tokens (that i know of). To keep it running you could fork the project and remove the token counting feature
