### ISSUE TITLE
type' object is not subscriptable 

### ISSUE THREAD

**Issue by kingofkillers91** [n3d1117/chatgpt-telegram-bot#90]
(venv) root@localhost:~/chatgpt-telegram-bot# python bot/main.py Traceback (most recent call last): File "bot/main.py", line 6, in <module> from openai_helper import OpenAIHelper File "/root/chatgpt-telegram-bot/bot/openai_helper.py", line 10, in <module> class OpenAIHelper: File "/root/chatgpt-telegram-bot/bot/openai_helper.py", line 26, in OpenAIHelper async def get_chat_response(self, chat_id: int, query: str) -> Union[tuple[str, str], str]: TypeError: 'type' object is not subscriptable

What's wrong? can you help? I followed your instructions step by step.

**Comment by carlsverre** [comment]
Can you verify that you are using python 3.5? I don't think earlier versions support type annotations.

**Comment by kingofkillers91** [comment]
Yep, now i installed it, but i get the same error.
![image_2023-03-21_142255096](https://user-images.githubusercontent.com/48602339/226619052-ccfe9c4e-3c10-4285-9006-8bd83bd61f72.png)

**Comment by carlsverre** [comment]
Perhaps a later version of python is required. I suggest upgrading to the latest version possible unless someone else has any other ideas. Also make sure that you are rebuilding the venv after changing python versions. And make sure that when you change python versions, the binary "python" and "python3" is updated to point at the new version. I personally use [pyenv](https://github.com/pyenv/pyenv) to manage my python stack.

**Comment by kingofkillers91** [comment]
I updated python to the latest ver, and created another env. Same problem unfortunately

How do i do this= And make sure that when you change python versions, the binary "python" and "python3" is updated to point at the new version????

**Comment by n3d1117** [comment]
@kingofkillers91 did you manage to fix this? python 3.9 is recommended

**Comment by kingofkillers91** [comment]
yes I fixed it. thanks
