### ISSUE TITLE
Group add

### ISSUE THREAD

**Issue by Abhirajhih** [n3d1117/chatgpt-telegram-bot#95]
Bot only respond if user join selected group

**Comment by n3d1117** [comment]
Can you elaborate? You want the bot to work only for users who are members of a selected group?

**Comment by Abhirajhih** [comment]
I created my own bot with this feature

**Comment by Abhirajhih** [comment]
You can message me on Telegram @Abuiraj_singh

**Comment by Abhirajhih** [comment]
Sorry @abhiraj_singh
